angular/README.md, angular/package.json, angular/projects/admin-nrced/src/app/app.module.ts, angular/projects/global/ng-package.json, angular/projects/global/package.json, angular/tsconfig.json, angular/tslint.json
- Added package.json scripts to build and symlink the library, as well as some commands for publishing whenever we get to that stage.
- Updated Readme to reflect the new way of building/running the app (as you need to account for the library, and build order matters).
- Updated some of the library configs.
=> PTI-143-3: Add symlink support for local library development.

angular/projects/admin-nrpti/src/app/import/import.component.ts, angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts, api/src/controllers/search.js
Reverts bcgov/NRPTI#68
I think we'll want to solve this a different way - search results should return something, just not [] on the main return unless it's an error.
=> Revert "PTI-81-2: Add .toArray() call to mongodb aggregate cursor result."

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts, angular/projects/admin-nrpti/src/app/records/records-resolver.ts, angular/projects/admin-nrpti/src/app/records/records-rows/records-table-row.component.html
- Update default sorting on admin records page.
- Temporarily remove download document column from admin records page.
=> PTI-339/PTI-340: Update default sorting, temporarily remove documents download column.

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts, angular/projects/admin-nrpti/src/app/records/records-rows/records-table-row.component.html, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.html, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.scss
This PR partially undoes this PR: https://github.com/bcgov/NRPTI/pull/105
And then comments out the download documents column from _public-nrced_, rather than admin-nrpti (derp).
=> PTi-339-2: Temporarily remove the correct download documents button.

angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html, angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.ts, angular/projects/admin-nrpti/src/app/records/inspections/inspection-lng-detail/inspection-lng-detail.component.html, angular/projects/admin-nrpti/src/app/records/inspections/inspection-lng-detail/inspection-lng-detail.component.ts, angular/projects/admin-nrpti/src/app/records/inspections/inspection-nrced-detail/inspection-nrced-detail.component.html, angular/projects/admin-nrpti/src/app/records/inspections/inspection-nrced-detail/inspection-nrced-detail.component.ts, angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.html, angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.ts, angular/projects/admin-nrpti/src/app/records/orders/order-lng-detail/order-lng-detail.component.html, angular/projects/admin-nrpti/src/app/records/orders/order-lng-detail/order-lng-detail.component.ts, angular/projects/admin-nrpti/src/app/records/orders/order-nrced-detail/order-nrced-detail.component.html, angular/projects/admin-nrpti/src/app/records/orders/order-nrced-detail/order-nrced-detail.component.ts, angular/projects/admin-nrpti/src/app/records/utils/record-detail.directive.ts, api/src/utils/query-actions.js
- Updated pub/unpub + UI handling
- Also included an update to the record-detail.directive because I noticed it was missing.  Matches the behaviour of the table-row.directive now to handle the input more correctly.
=> PTI-258-3: Improve Publish/Unpublish logic + UI date handling.

angular/projects/admin-nrpti/src/app/app.module.ts, angular/projects/admin-nrpti/src/app/services/api.service.ts, angular/projects/admin-nrpti/src/app/services/factory.service.ts, angular/projects/admin-nrpti/src/app/services/task.service.ts
Aligns the task request with our current services style.
=> Add Task Service.

angular/projects/public-lng/src/app/project/authorizations/authorizations-rows/authorizations-table-rows.component.scss, angular/projects/public-lng/src/app/project/compliance/compliance-rows/compliance-table-rows.component.scss, angular/projects/public-lng/src/app/project/nations/nations-rows/nations-table-rows.component.scss, angular/projects/public-lng/src/app/project/plans/plans-rows/plans-table-rows.component.scss, angular/projects/public-lng/src/assets/styles/components/pagination.scss, angular/projects/public-lng/src/assets/styles/themes/default.scss
- Change LNG table hover colour to not be super dark.
- Update the pagination.scss to match admin-nrpti and public-nrced.
- Unifies the pagination controls look and feel.
=> PTI-387: Update public-lng media-queries and related scss.

angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.scss, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.scss, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.scss, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.scss
Tweak 1 scss setting that was out of sync between the details pages.
=> PTI-387: Add media-queries to order and inspections (to match the other NRCED types).

angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/agreements/agreement-add-edit/agreement-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-add-edit/construction-plan-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.html
Update the word 'hitting' to 'clicking'
=> PTI-410: Update wording/spelling.

angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html, angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html, angular/projects/admin-nrpti/src/app/records/agreements/agreement-detail/agreement-detail.component.html, angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/certificates/certificate-detail/certificate-detail.component.html, angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-detail/construction-plan-detail.component.html, angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html, angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-detail/management-plan-detail.component.html, angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.html, angular/projects/admin-nrpti/src/app/records/permits/permit-detail/permit-detail.component.html, angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html, angular/projects/admin-nrpti/src/app/records/self-reports/self-report-detail/self-report-detail.component.html, angular/projects/admin-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html, angular/projects/admin-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.html, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html
Commit 1:
- Add attachments code to public-nrced details UI.
Commit 2:
- Update attachments code in admin-details
- I removed the check on sourceSystemRef since that field gets deleted on edit currently, and was being checked in the HTML when adding attachments. (related to the dirty-fields bug).
Commit 3:
- Pass attachments through the admin add-edit pages so they don't get deleted on edit. 
- Short-term fix due to the dirty-fields bug. 
- I only updated the 4 record types that have epic importers, since no other records currently can have attachments.
=> PTI-410: Make attachments show on public-nrced

api/src/integrations/epic/epic-datasource.js
It now runs each record type in parallel.
Within the record type, after it fetches records from epic, it processes and saves them all in parallel.
This is an example of the ultimate status object that gets produced, from the import currently, mostly because its interesting and we talked about it before.  The task audit data we log hasn't changed or anything.
```
{
"itemsProcessed": 1640,
"itemTotal": 1644,
"typeStatus": [
{
"type": {
"type": {
"name": "Order",
"typeId": "5cf00c03a266b7e1877504d1"
},
"milestone": {
"name": "Other",
"milestoneId": "5d0d212c7d50161b92a80eed"
}
},
"itemTotal": 2,
"url": "https://eagle-prod.pathfinder.gov.bc.ca/api/public/search?dataset=Document&populate=false&pageSize=9007199254740991&pageNum=0&and%5Btype%5D=5cf00c03a266b7e1877504d1&and%5Bmilestone%5D=5d0d212c …
```
=> PTI-400: Update epic-import to parallelize all the things.

angular/projects/public-lng/src/app/project/authorizations/authorizations.component.ts, angular/projects/public-lng/src/app/project/compliance/compliance-resolver.ts, angular/projects/public-lng/src/app/project/compliance/compliance.component.html, angular/projects/public-lng/src/app/project/compliance/compliance.component.ts, angular/projects/public-lng/src/app/project/plans/plans-resolver.ts, angular/projects/public-lng/src/app/project/plans/plans.component.html, angular/projects/public-lng/src/app/project/plans/plans.component.ts
Adds remaining filters on public LNG.  Changes filters based on what's in the column/data.
=> PTI-405: Updated filters

angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-add-edit/construction-plan-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-detail/construction-plan-detail.component.html, angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-detail/construction-plan-detail.component.scss, angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-detail/management-plan-detail.component.html
Add 'Author' to the details UI.
=> PTI-404: Tweaks to Management/Construction Plan UI.

api/src/integrations/epic/datasource.js
- For each supported type, run updates in parallel.
- For each record of that type, run update in parallel.
- For each supported type, run updates in parallel.
- For each record of that type, run update in batches of 50.
=> PTI-400: Reduce epic-import parallelization. Update projects url.

angular/package-lock.json, angular/projects/admin-nrpti/src/app/import/import.component.ts, api/src/integrations/epic/datasource.js, api/src/integrations/epic/datasource.test.js, api/src/integrations/integration-utils.js, api/src/integrations/integration-utils.test.js, api/src/integrations/nris/datasource.js, api/src/integrations/nris/datasource.test.js, api/src/models/master/inspection.js, api/src/tasks/import-task.js, api/src/utils/mongodb.js, tools/jenkins/openshift/api/api-dc.json
Stubs in the first cut of NRIS import task.
=> PTI-7: NRIS migration

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.html, angular/projects/admin-nrpti/src/app/utils/constants/record-constants.ts
Added a new value to the issuing agency picklist.
Updated an existing value in the issuing agency picklist.
Alphabetized all picklists (see comment added to the picklists object).
Alphabetized the order of the records in the manual add drop-down menu.
=> PTI-416: Update Issuing Agency picklist (includes PTI-431).

angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts, angular/projects/admin-nrpti/src/app/services/document.service.ts, angular/projects/admin-nrpti/src/app/services/factory.service.ts, api/src/controllers/document-controller.js, api/src/controllers/post/order.js, api/src/controllers/put/order.js, api/src/models/master/administrativePenalty.js, api/src/models/master/administrativeSanction.js, api/src/models/master/agreement.js, api/src/models/master/certificate.js, api/src/models/master/constructionPlan.js, api/src/models/master/inspection.js, api/src/models/master/managementPlan.js, api/src/models/master/order.js, api/src/models/master/permit.js, api/src/models/master/restorativeJustice.js, api/src/models/master/selfReport.js, api/src/models/master/ticket.js, api/src/models/master/warning.js, api/src/swagger/swagger.yaml
Signed-off-by: Daniel Truong <daniel@dtsoftware.ca>
=> PTI-257: Updating order of operations for add doc.

angular/projects/admin-nrpti/src/app/records/common-components/legislation-add-edit/legislation-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/common-components/legislation-add-edit/legislation-add-edit.component.ts, angular/projects/admin-nrpti/src/app/utils/constants/record-constants.ts, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.html, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html, angular/projects/public-nrpti/src/assets/styles/components/record-details.scss
- Fixed title attribute on act and reg dropdowns.
- Fixed act and reg dropdown reset logic.
- Added more acts/regs to the constants list.
- Update act and reg filter logic to be AND (rather than OR).
- Updated some scss to make legislation on public-nrced display nicer.
=> PTI-449: legislation improvements

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
Issue:
Was sorting by the entire object
Fix:
It now sorts by issuedTo.fullName, as appropriate.
=> Fix sorting by issuedTo.

api/migrations/20200406231253-keywordIndex.js, api/src/models/nrced/administrativePenalty-nrced.js, api/src/models/nrced/administrativeSanction-nrced.js, api/src/models/nrced/inspection-nrced.js, api/src/models/nrced/order-nrced.js, api/src/models/nrced/restorativeJustice-nrced.js, api/src/models/nrced/ticket-nrced.js, api/src/models/nrced/warning-nrced.js
Remove index object from some models.
=> PTI-496: Adding text indexes via migrator.

api/src/integrations/epic/base-record-utils.js, api/src/integrations/epic/base-record-utils.test.js, api/src/integrations/epic/datasource.js, api/src/integrations/epic/datasource.test.js, api/src/integrations/nris/datasource.js, api/src/tasks/import-task.js
- Add EPIC start date filter
- Add NRIS end date filter
- Update NRIS imported to create flavour records, and publish.
=> PTI-507: Update epic and nris importers.

angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html, angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.html, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.html, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html
Had previously added logic to show 'Unpublished' if the issuedTo object was redacted but didn't add this to the expanded details view.
=> Add IssuedTo 'Unpublished' - Expanded details view

angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts, api/src/integrations/epic/inspections-utils.js, api/src/integrations/epic/orders-utils.js
PTI-516/PTI-522: Epic Import: fix legislation typo, fix proponent company name.
PTI-517: NRCED filters: update to allow both company and individual filters.
=> Various Release Fixes

api/migrations/20200109220142-projectData.js
Just something I noticed when doing other stuff.
=> NOBUG: Fix migration document read roles

angular/projects/public-nrpti/src/app/app.component.html, angular/projects/public-nrpti/src/assets/styles/components/spinner.scss
Previously, added some transparency to the Admin spinners, but didn't think to update the NRCED ones to match.
=> Add transparency to spinner on Nrced, to match Admin.

api/src/integrations/nris/datasource.js
- now distinguishes between companies and individuals when setting issuedTo
=> PTI-559: update nris import for issuedTo

angular/projects/admin-nrpti/src/assets/styles/components/pagination.scss, angular/projects/admin-nrpti/src/assets/styles/themes/default.scss, angular/projects/common/src/assets/styles/themes/default.scss, angular/projects/public-lng/src/assets/styles/components/pagination.scss, angular/projects/public-lng/src/assets/styles/themes/default.scss, angular/projects/public-nrpti/src/assets/styles/components/pagination.scss, angular/projects/public-nrpti/src/assets/styles/themes/default.scss
The colour of the pagination control was different than the other elements on the sites.  Updated to use the colour `#036` to match.  
Also made a minor tweak to the pagination scss so that the hover effect matches that of the # of records per page component (it was close before, but not quite right).
=> PTI-605: Update pagination control colour and hover effect

api/migrations/20200211065122-nrcedData.js
- Also update the subSection and paragraph regex to be more robust.
=> PTI-583: Update ocers-data.csv

angular/projects/admin-nrpti/src/app/news/news-add-edit/news-add-edit.component.ts, angular/projects/common/src/app/utils/record-constants.ts, angular/projects/public-lng/src/app/project/overview/overview.component.ts, angular/projects/public-lng/src/app/services/api.ts, api/migrations/20200109220142-projectData.js, api/migrations/20200603212940-fixLNGCGLIDs.js, api/src/integrations/epic/epic-record-type-enum.js
This requires a deployment to API and the front-ends.
Once complete, running DB-migrate will fix all the IDs for the various assets.
After that, we can go to record: 5ebaed23516bac001aeff618 and switch it to LNG using the front-end.
=> NRPT-143: Fix misaligned LNG / CGL ID's

angular/projects/admin-nrpti/src/app/explore-panel/explore-panel.component.html, angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts, angular/projects/admin-nrpti/src/app/records/records-resolver.spec.ts, angular/projects/admin-nrpti/src/app/records/records-resolver.ts, angular/projects/admin-nrpti/src/app/services/factory.service.ts, angular/projects/global/src/lib/services/search.service.ts, angular/projects/public-nrpti/src/app/services/factory.service.ts, api/src/controllers/search.js, api/src/swagger/swagger.yaml, api/src/tests/controllers/search.test.js
- Add Projects advanced filters,
- Add unit tests.
- I put a bit of a timebox on the tests, since many of these classes don't have any at the moment, and I could easily spend over a week just writing tests.  I focused on testing only the code that was new or directly touched as a result of this feature, in the 2 spots that are the most impactful and most likely to run into issues if changes are made in future.
- Linted the files that were touched.
- Code review updates
=> NRPT-70: Admin Projects Filter

api/app.js, api/src/controllers/post/mine.js, api/src/controllers/put/mine.js, api/src/controllers/record-controller.js, api/src/integrations/core/base-record-utils.js, api/src/integrations/core/datasource.js, api/src/integrations/core/mine-utils.js, api/src/models/bcmi/mine.js, api/src/models/master/mine.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-109
Adds an importer that retrieves new and updated records from Core. The importer was created to be run as a system job rather than one that is triggered by the user. The CRON is not part of this ticket as there is another ticket to handle creating the scheduling.
Note:
There are no tests. Will be adding those in a separate PR, but wanted to get this in to unblock others
There will most likely need to be some changes to a mine's commodities, but it is currently fetching that data the best way we know how
The last AC on the ticket mentions providing error feedback to the user. This is done through logging as this is not a user-triggered job
=> Adds Core API integration

angular/projects/admin-nrpti/src/app/explore-panel/explore-panel.component.ts, angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.html, angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
https://bcmines.atlassian.net/browse/NRPT-67
- explore panel component now emits when the reset button is clicked
- changed records list component sortBy logic
=> NRPT-67: Update sortBy logic in admin search

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.html, api/materialized_views/search/descriptionSummarySubset.js, api/materialized_views/updateViews.js, api/migrations/20200609000239-recreateDescriptionSummarySubsetTextIndex.js, api/src/controllers/search.js
https://bcmines.atlassian.net/browse/NRPT-71
- Add description & summary option to admin keyword search
- Add description subset
- Add new description_summary_subset text index migration
Including just the description & summary part of this ticket.  
The final piece in the ticket is to add the recordName search, which I will add in a separate PR, as long as this one is on the right track.
=> NRPT-71: Description & Summary keyword search.

api/src/integrations/core/mine-utils.js, api/src/integrations/core/mine-utils.test.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-163
Updates the Core importer to map the status and commodities properly.
=> NRPT-163: Updates Core importer mapping

tools/jenkins/openshift/api/api-dc.json
Updates the DC to use the secrets required to connect to the Core API.
=> NOBUG: Updates deployment config to attach Core API secrets

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.html, angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
Adding the clear keyword button to the text box for keyword searches in the record search page.
See ticket [NRPT-164](https://bcmines.atlassian.net/browse/NRPT-164)
=> NRPT-164: Adding clear keywords button to keyword box

api/src/integrations/core/datasource.js
=> NOBUG: Fix method name

angular/projects/public-lng/src/assets/data/project1/compliance.json, angular/projects/public-lng/src/assets/data/project2/compliance.json
-  Business had additional changes
=> NRPT-234: Additional LNG Compliance Text changes

angular/projects/public-nrpti/src/app/app-routing.module.ts, angular/projects/public-nrpti/src/app/home/home.component.html, angular/projects/public-nrpti/src/app/home/home.component.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
See ticket [NRPT-226](https://bcmines.atlassian.net/browse/NRPT-226)
=> NRPT-226: Add more info paragraph, link

angular/projects/common/src/app/utils/record-constants.ts
Re-ordered the list alphabetically, added `core`
=> NRPT-239: Enable filtering of CORE records.

api/src/controllers/search.js
Adding a published field to search results to support sorting by published.
See ticket [NRPT-248](https://bcmines.atlassian.net/browse/NRPT-248)
=> NRPT-248: Add a published field to search results

angular/projects/common/src/app/utils/record-constants.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
NRCED public schema list was set to use the admin schemas. Updated list to use public schemas.
See ticket [NRPT-257](https://bcmines.atlassian.net/browse/NRPT-257)
=> NRPT-257: Fix to NRCED public base schema list

angular/projects/admin-nrpti/src/app/mines/mines-collections-list-resolver.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list-resolver.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.scss, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.scss, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-content/mines-content.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-routing.module.ts, angular/projects/admin-nrpti/src/app/mines/mines-rows/mines-table-row.component.scss, angular/projects/admin-nrpti/src/app/mines/mines.module.ts, angular/projects/admin-nrpti/src/app/services/factory.service.ts, angular/projects/admin-nrpti/src/app/services/record.service.ts, angular/projects/admin-nrpti/src/app/shared/shared.module.ts, angular/projects/common/src/app/models/bcmi/collection-bcmi.ts, angular/projects/common/src/app/models/bcmi/index.ts, api/src/controllers/record-controller.js, api/src/controllers/search.js, api/src/models/bcmi/collection-bcmi.js, api/src/models/bcmi/index.js, api/src/swagger/swagger.yaml, api/src/tests/controllers/search.test.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-195
- add mines collections list page
- add new functions + swagger route for deleting a collection
- minor updates to the mines records list page based on improvements found while developing the collections list page
- add collection-bcmi.ts
- rename collection.js to collection-bcmi.js to be consistent
- add array count field to search.js, for bcmi records count sorting
- add tests for new function to search.test.js
=> NRPT-195: Mines collections list page

angular/projects/common/src/app/utils/record-constants.ts
Adding back in Wildfire Act (regulation, section, subsection, act descriptions already in place)
See ticket [NRPT-213](https://bcmines.atlassian.net/browse/NRPT-213)
=> NRPT-213: Add Wildfire Act

angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
See ticket [NRPT-128](https://bcmines.atlassian.net/browse/NRPT-128)
=> NRPT-128: Set default sort to dateIssued in NRCED

api/migrations/20200707231924-clearMineSchemas.js, api/src/integrations/core-documents/datasource.js
Drops all Core related records so that a fresh import from Core can happen.
Also updates document importer to match new document property.
=> NOBUG: Drop all Core related records

api/src/importers/bcogc/base-record-utils.js, api/src/importers/bcogc/base-record-utils.test.js, api/src/importers/bcogc/inspections-utils.js, api/src/importers/bcogc/inspections-utils.test.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-251
- Sets summary field for nrced flavour records
- Update tests as needed
No longer sure who has the most time for PRs, so just spammed everyone
=> NRPT-251: Update BCOGC csv importer

angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail-record-row/mines-collection-detail-record-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.scss, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-routing.module.ts, angular/projects/admin-nrpti/src/app/mines/mines-rows/mines-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines.module.ts, angular/projects/admin-nrpti/src/app/services/factory.service.ts, angular/projects/admin-nrpti/src/assets/styles/components/drag-drop.scss, angular/projects/common/src/app/utils/record-constants.ts, api/src/controllers/post/collection-bcmi.js, api/src/controllers/put/collection-bcmi.js, api/src/controllers/record-controller.js, api/src/controllers/search.js, api/src/swagger/swagger.yaml, api/src/utils/constants/record-type-enum.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-196
- Add mine collections add-edit component
- Update search.js to populate collection records
- Add collection post/put controllers
- Misc tweaks
=> NRPT-196: Mine Collections add-edit

angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collection-resolver.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list-resolver.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.html, angular/projects/admin-nrpti/src/app/mines/mines-list-resolver.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-list-resolver.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.html, angular/projects/admin-nrpti/src/app/services/factory.service.ts, angular/projects/admin-nrpti/src/assets/styles/components/mine.scss, angular/projects/admin-nrpti/src/assets/styles/themes/default.scss, angular/projects/common/src/app/utils/record-constants.ts
Ticket: https://bcmines.atlassian.net/browse/NRPT-241
=> NRPT-241: Multi-select add records to collection

angular/projects/common/src/app/search-filter-template/search-filter-template.component.html, angular/projects/common/src/app/search-filter-template/search-filter-template.component.scss
Bolding all labels, padding on date filter inputs for better spacing on staggered forms
See ticket [NRPT-199](https://bcmines.atlassian.net/browse/NRPT-199)
=> NRPT-199: Common search style updates

api/openshift/cron.yaml
Adds the CORE documents import task to the cron template.
=> NOBUG: Adds core document to cron template

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.ts
Ticket: https://bcmines.atlassian.net/browse/NRPT-198
Adds the ability to select records from the records list and add them to a new or existing collection.
=> NRPT-198: Link records to collection

angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.scss
Truncates long mine record names and adds the date issued as a display field.
=> NOBUG: Mine Record Detail Update

api/src/controllers/search.js
API update to allow for public fetching of records/documents for the BCMI UI.
See Ticket [NRPT-302](https://bcmines.atlassian.net/browse/NRPT-302)
=> NRPT-302: Item search update for public collection records fetching

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts
Removed the pencil from the table, removed 'remove record' option from the ellipsis menu.
See ticket [NRPT-290](https://bcmines.atlassian.net/browse/NRPT-290)
=> NRPT-290: Removed edit, details options from collection record view

angular/projects/common/src/app/models/bcmi/permit-bcmi.ts, angular/projects/common/src/app/models/master/permit.ts, api/src/controllers/post/permit.js, api/src/integrations/core/permit-utils.js, api/src/models/bcmi/permit-bcmi.js, api/src/models/lng/permit-lng.js, api/src/models/master/permit.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-276
Most of the work had already been completed. The only thing missing was the IssuedTo field.
=> NRPT-276: Adds issued to to permit

angular/projects/admin-nrpti/src/app/mines/mines-collections-list-resolver.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts, api/src/controllers/search.js
Adds remaining filters to the collections advanced filters. Implements Record filter.
See ticket [NRPT-283](https://bcmines.atlassian.net/browse/NRPT-283)
=> NRPT-283: Update collection advanced filters

angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.scss
Adds some descriptive text to the mine add/edit pages description and summary text labels.
See ticket [NRPT-278](https://bcmines.atlassian.net/browse/NRPT-278)
=> NRPT-278: Adding descriptive text

angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.html, angular/projects/admin-nrpti/src/assets/styles/base/helpers.scss
Ticket: https://bcmines.atlassian.net/browse/NRPT-256
Changes: Mines details screen will maintain any whitespace (spaces and line breaks) that is input in the edit/add screens.
=> NRPT-256: Maintains whitespace in mine description and summary

api/src/integrations/nris-epd/datasource.js
Fixes the NRIS importer... removed testing code.
=> NOBUG: Fix NRIS importer

angular/projects/admin-nrpti/src/app/documents/documents.module.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines.module.ts, angular/projects/admin-nrpti/src/app/records/records.module.ts
Updates the permit record detail screen to use the authenticated document component.
=> NOBUG: Makes permit documents use authenticated call

api/src/integrations/epic/orders-utils.js
- [NRPT-261](https://bcmines.atlassian.net/browse/NRPT-261)
=> update order section number, remove subsection

angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail-record-row/mines-collection-detail-record-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.scss
Some minor fixes to the Mines records list pages handling for published states, sorting.
See tickets [NRPT-338](https://bcmines.atlassian.net/browse/NRPT-338), [NRPT-339](https://bcmines.atlassian.net/browse/NRPT-339), [NRPT-343](https://bcmines.atlassian.net/browse/NRPT-343)
=> NRPT-338: List published fixes

angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.html
See tickets [NRPT-312](https://bcmines.atlassian.net/browse/NRPT-312) and [NRPT-313](https://bcmines.atlassian.net/browse/NRPT-313)
=> NRPT-312: Update button text, hide actions on collection state

angular/projects/admin-nrpti/src/index.html, angular/projects/public-lng/src/index.html, angular/projects/public-nrpti/src/index.html
See tickets [NRPT-330](https://bcmines.atlassian.net/browse/NRPT-330), [NRPT-331](https://bcmines.atlassian.net/browse/NRPT-331) and [NRPT-332](https://bcmines.atlassian.net/browse/NRPT-332)
=> NRPT-330: Snowplow updates

api/migrations/202008241608531-fixDocumentPermissions.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-348
This migration checks if a Document record is public or not and then updates the S3 permissions accordingly.  The ticket only calls for documents that are public to be updated but I opted to update ones that are not public as well just to be sure.
=> NRPT-348: Set Document Permissions

angular/projects/admin-nrpti/src/app/import/import-list-resolver.ts
Swapped the Import list sort order.
See ticket [NRPT-206](https://bcmines.atlassian.net/browse/NRPT-206)
=> NRPT-206: Default order for import list

angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.html, angular/projects/common/src/app/search-filter-template/readme.md, angular/projects/common/src/app/search-filter-template/search-filter-template.component.html, angular/projects/common/src/app/search-filter-template/search-filter-template.component.ts
Added a Keyword text box watermark input for the common search controller, added an updated label for the mines search box.
See Ticket [NRPT-215](https://bcmines.atlassian.net/browse/NRPT-215)
=> NRPT-215: Adding keyword watermark to search box

angular/projects/public-lng/src/app/project/plans/plans-rows/plans-table-rows.component.html
Ticket: https://bcmines.atlassian.net/browse/NRPT-358
Fixes the agency display for LNG project plan records.
=> NRPT-358: Fix Agency Display

api/src/integrations/nris-epd/datasource.js
make sure new record obj has documents array filled
- [NRPT-359](https://bcmines.atlassian.net/browse/NRPT-359)
=> NRPT-359: add check for existing documents and populate documents 

api/migrations/20200709183253-loadMemDocs.js, api/migrations/202008241608531-fixDocumentPermissions.js
Fixes two issues with two migrations.
=> NOBUG: Fixes two migrations

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.html
- [NRPT-395](https://bcmines.atlassian.net/browse/NRPT-395)
- [NRPT-398](https://bcmines.atlassian.net/browse/NRPT-398)
- [NRPT-397](https://bcmines.atlassian.net/browse/NRPT-397)
=> NRPT-395: update helper text and labels on collection page

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.html, angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.ts, api/migrations/20200914210739-fixIsBcmiPublishedField.js, api/src/controllers/collection-controller.js
https://bcmines.atlassian.net/browse/NRPT-315
Collections are automatically public.
Collections require a record to be saved.
Records added to a collection are public.
Records removed from a collection are unpublished.
When creating a record in mines, if not associated with a collection, is not public.
=> NRPT-315: auto-publish bcmi flavour records

angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail-record-row/mines-collection-detail-record-row.component.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-collection-detail/mines-collection-detail-record-row/mines-collection-detail-record-row.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-rows/mines-table-row.component.spec.ts
https://bcmines.atlassian.net/browse/NRPT-410
=> NRPT-410: Collection detail record row goes to record details

angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.ts
In mines records list, edit button is moved into ellipses.
Clicking anything in the ellipses will now open a new tab.
https://bcmines.atlassian.net/browse/NRPT-401
https://bcmines.atlassian.net/browse/NRPT-403
=> NRPT-401 and NRPT-403: Moved edit record button into ellipses

api/migrations/20200709183253-loadMemDocs.js
Tested against latest test DB
- [NRPT-418](https://bcmines.atlassian.net/browse/NRPT-418)
=> update loadMem migration with checks for existing docs and collections

api/migrations/20200709183253-loadMemDocs.js, api/migrations/202009222308229-fixMemAdminDocs.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-424
Fixes an issue where not all collections where being displayed on the public side.  This was due to all mem-admin imported collections containing documents that were missing the 'read' permission.
=> NRPT-425: Fixes Permissions with Imported Documents

angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.html
Ticket: https://bcmines.atlassian.net/browse/NRPT-449
Removes the link to upload documents from within a mine.
=> NRPT-449: Remove Upload Document Option

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.html
https://bcmines.atlassian.net/browse/NRPT-309
=> NRPT-309: right aligned all records dropdown

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts
Ticket: https://bcmines.atlassian.net/browse/NRPT-444
Fixes: Resolves issue where an error message would appear when deleting a collection even though the deletion was successful.
=> NRPT-444: Fixes Delete Message Popup

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts, angular/projects/admin-nrpti/src/app/news/news-add-edit/news-add-edit.component.html, angular/projects/admin-nrpti/src/app/news/news-routing.module.ts, api/src/controllers/news-controller.js, api/src/controllers/post/post.js
Noticed issues with collection add and news add.
=> Fixed error with collection add

api/migrations/20200709183253-loadMemDocs.js
This fixes the document load script so that blank documents are not added to S3.
=> NOBUG: Fixes Mem Migration

api/src/controllers/collection-controller.js, api/src/integrations/core/collection-utils.js, api/src/integrations/core/datasource.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-482
Fixes the Core importer so that it create's collections on import. Issue was caused because the importer was not updated to handle the new controller structure.
=> NRPT-482: Fixes Core Importer Collection Creation

api/migrations/20200709183253-loadMemDocs.js
[NRPT-456](https://bcmines.atlassian.net/browse/NRPT-456) Decided to just make the logging more verbose for these documents that aren't migrated correctly, so we can track and deal with them later.
=> NRPT-456: Added verbose logs for failed mem doc imports

api/src/controllers/collection-controller.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-490
When collections were published/unpublished it did not filter down to the permissions on the S3 objects. I have added the permission updates to these objects as part of the collection's actions.
=> NRPT-490: Fix Document Permission S3

angular/projects/common/src/app/utils/record-constants.ts
Ticket: https://bcmines.atlassian.net/browse/NRPT-317
Updates the descriptions of some records and adds new descriptions for some others.
=> NRPT-317: Updates Record Descriptions

api/migrations/20201022185353-fixNRISImportEmptyDocuments.js, api/src/controllers/post/inspection.js, api/src/controllers/put/inspection.js, api/src/integrations/nris-epd/datasource.js, api/src/utils/put-utils.js
https://bcmines.atlassian.net/browse/NRPT-468
- Fixed Inspection flavor records having empty documents array when NRIS import fails to download attachment
- Added migration to fix existing flavour records
=> NRPT-468 Fix NRIS missing documents on NRCED (and other flavours) records

api/migrations/20201007180748-setMasterRefOnFlavours.js
- [NRPT-498](https://bcmines.atlassian.net/browse/NRPT-498)
=> NRPT-498: fix missing LNG activities

api/migrations/20200709183253-loadMemDocs.js, api/src/models/bcmi/collection-bcmi.js
Wanting to land this before UI work is complete so that we can reference it later.
=> NRPT-500: Model changes for tracking source creation of collection.

angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.html
No need for migration as another data load will be after this is pushed.
=> NRPT-500: Visualize source for collection.

api/migrations/20200709183253-loadMemDocs.js
- [NRPT-496](https://bcmines.atlassian.net/browse/NRPT-496)
=> NRPT-496: fix records with bad collection ids

api/src/controllers/collection-controller.js
https://bcmines.atlassian.net/browse/NRPT-501
- Fixed mineGuid not being remove when record is removed from collection
=> NRPT-501 Fix records still associated with mine when removed from mine collection

api/src/utils/s3-cleanup.js
https://bcmines.atlassian.net/browse/NRPT-497
=> NRPT-497 Create S3 object clean up script

api/src/controllers/collection-controller.js, api/src/integrations/core/datasource.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-503
Part two of this ticket's fixes. Updated the collection controller to set new collection's published status based on that of the mine. Also updated to set the document's status based on that of the collection (which is based on the mine).
=> NRPT-503: Collection Updates

api/migrations/20200724171605-bcmiDataLoad.js
https://bcmines.atlassian.net/browse/NRPT-507
=> NRPT-507  BCMI data load permit mapping for Fording River Operations

api/migrations/20200709183253-loadMemDocs.js
[NRPT-496](https://bcmines.atlassian.net/browse/NRPT-496)
- removes records from existing collections that they don't belong to
=> NRPTI-496-2: refine the collection lookup query and fix existing collections

api/src/controllers/config.js, tools/jenkins/openshift/api/api-dc.json
https://bcmines.atlassian.net/browse/NRPT-519
=> NRPT-519 Add Geocoder API to config service

api/migrations/20200709183253-loadMemDocs.js, api/src/models/bcmi/collection-bcmi.js, api/src/models/bcmi/permit-bcmi.js
[NRPT-496](https://bcmines.atlassian.net/browse/NRPT-496)
=> fix loadMemDoc issue with records being added to multiple collections

api/src/integrations/nris-epd/datasource.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-308
This updates the NRIS importer to dynamically set the legislation based on the incoming record's requirement source. Previously the legislation was hard-coded to a single value.
=> NRPT-308: Updates NRIS Legislation Criteria

api/migrations/202011061404133-removeDevDocuments.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-530
The errors in this ticket were caused by documents that referenced the Dev S3 bucket. Those documents no longer exist in the Dev S3 so they are going to be manually added.  This migration removes them so the mines can be published.
=> NRPT-530: Removes Documents Referencing Dev S3

api/src/integrations/core/datasource.js, api/src/integrations/core/mine-utils.js
[NRPT-537](https://bcmines.atlassian.net/browse/)
=> NRPT-537: fix permittee and permit number not updating when core data does

api/package.json, api/src/controllers/post/order.js, api/src/integrations/bcogc/datasource.js, api/src/integrations/bcogc/orders-utils.js, api/src/integrations/bcogc/utils/csv-utils.js, api/src/models/lng/order-lng.js, api/src/models/master/order.js, api/src/models/nrced/order-nrced.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-363
Adds the BCOGC orders to the BCOGC import button.  Orders are scraped from a page as there is no endpoint to generate the CSV.
=> NRPT-363: Adds BCOGC Order Importer

angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.spec.ts, angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.html, angular/projects/common/src/app/models/bcmi/mine.ts, api/migrations/202011181302125-addMinePermitFlag.js, api/src/models/bcmi/mine-bcmi.js
Ticket: https://bcmines.atlassian.net/browse/NRPT-525
This tickets adds the ability to choose if users of BCMI should see the permit number in the name of EMPR collections. This PR goes along with one in mem-mmti-public.
=> NRPT-525: Hide EMPR Permit Number

api/migrations/20201117185607-addCoreCollectionRefId.js, api/package-lock.json, api/src/controllers/collection-controller.js, api/src/integrations/core/collection-utils.js, api/src/integrations/core/datasource.js, api/src/integrations/core/permit-utils.js, api/src/models/bcmi/collection-bcmi.js
https://bcmines.atlassian.net/browse/NRPT-549
- Added `20201117185607-addCoreCollectionRefId.js` migration to associate collections with the `permit_amendment_guid` from Core using the existing `_sourceRefId` on permit records
- Refactored Collection controller so the update function can be called directly from another file
- Added logic to update collections and records if changes are detected
Make sure to run the migration first if testing locally
=> NRPT-549 Fix Core importer not updaing collections and records

api/src/integrations/bcogc/orders-utils.js
Changes the description field for BCOGC order imports.
=> NOBUG: Changes BCOGC Description Field

angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.html
https://bcmines.atlassian.net/browse/NRPT-550
Fixed inconsistent date display issues between mine records list and record detail pages.
=> NRPT-550 Fix Mine records list not displaying parsed date

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.html, angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts, angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts, angular/projects/common/src/app/utils/record-constants.ts, api/src/importers/nro/base-record-utils.js, api/src/importers/nro/base-record-utils.test.js, api/src/importers/nro/datasource.js, api/src/importers/nro/datasource.test.js, api/src/importers/nro/inspections-utils.js, api/src/importers/nro/inspections-utils.test.js, api/src/importers/nro/utils/csv-utils.js, api/src/importers/nro/utils/csv-utils.test.js, api/src/tasks/import-task.js
https://bcmines.atlassian.net/browse/NRPT-12
NRO Inspections CSV import.  Please use this [sample file](https://chat.pathfinder.gov.bc.ca/group/7yTf7q3mWbKBAn2qa?msg=JPivWJQyAGTPXph2i) to test.
=> NRPTI-12 NRO Inspections CSV import

api/src/controllers/search.js, api/src/importers/nro/base-record-utils.js, api/src/importers/nro/base-record-utils.test.js, api/src/importers/nro/inspections-utils.js, api/src/importers/nro/inspections-utils.test.js
https://bcmines.atlassian.net/browse/NRPT-12
- Updated code so all records are published by default
- Entities other than LNG and CGL have birthday set as current date so their names will be redacted on the public sites
- Fixed issuing agency name
=> NRPT-12 Fix NRO importer publish

angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.ts, api/src/controllers/collection-controller.js, api/src/controllers/document-controller.js, api/src/controllers/record-controller.js
[NRPT-544](https://bcmines.atlassian.net/browse/NRPT-544)
=> NRPT-544: cleanup promise chain in bcmi collection controller

api/src/controllers/search.js
[NRPT-577](https://bcmines.atlassian.net/browse/NRPT-577)
=> NRPT-577: add objectId is valid check on id param

api/src/swagger/swagger.yaml
https://bcmines.atlassian.net/browse/NRPT-555
Adding `admin:wf` to the following
* `GET /search`
* `DELETE /record/{recordId}`
*  `POST /record/{recordId}/publish`
* `POST /record/{recordId}/unpublish`
* `POST /record`
* `PUT /record`
* `POST /record/{recordId}/document`
* `DELETE /record/{recordId}/document/{docId}`
* `GET /document/{docId}/signedurl`
=> NRPT-555 Add Wildfire role to Swagger routes

api/src/controllers/post/warning.js, api/src/integrations/bcogc/bcogc-utils-types-enum.js, api/src/integrations/bcogc/datasource.js, api/src/integrations/bcogc/warnings-utils.js, api/src/integrations/bcogc/warnings-utils.test.js, api/src/models/lng/warning-lng.js, api/src/models/master/warning.js, api/src/models/nrced/warning-nrced.js
[NRPT-365](https://bcmines.atlassian.net/browse/NRPT-365)
=> NRPT-365: import bcogc warnings from csv table

api/migrations/20201208212602-addPublicToMaster.js
https://bcmines.atlassian.net/browse/NRPT-582
=> NRPT-582 Add public read to master records with published flavours

api/migrations/20201210002351-companiesPublicRead.js, api/src/controllers/search.js, api/src/utils/auth-utils.js
- [NRPT-556](https://bcmines.atlassian.net/browse/NRPT-556)
=> NRPT-556: update search controller to redact issuedTo based on role

api/migrations/20201214191137-removeDuplicateNrisRecords.js, api/src/integrations/nris-epd/datasource.js
https://bcmines.atlassian.net/browse/NRPT-541
The original ticket was to investigate missing docs in NRIS import records.  The actual issue is there were duplicate records and the duplicates didn't have docs.  The duplicates never get updated by the importer because they're not selected as an "existing" record.
This PR introduces a migration to remove the duplicates. There are also some minor NRIS importer improvements
=> NRPT-541 Fix NRIS Importer duplicates and minor improvements

api/src/controllers/search.js
- [NRPT-556](https://bcmines.atlassian.net/browse/NRPT-556)
- addresses bug with flavours and documents not populating in details page
=> NRPT-556: fix flavours not showing in record detail view

api/src/controllers/search.js
- related to [NRPT-556](https://bcmines.atlassian.net/browse/NRPT-556)
Clicking a mine in BCMI should properly load the mine details. 
In NRPTI mine detail, record detail, collection detail, and all records should load correctly
=> NOBUG: skip redaction if schema is mineBCMI

api/openshift/cron.yaml
https://bcmines.atlassian.net/browse/NRPT-351
=> NRPT-351 Add NRIS-EPD to cron

angular/projects/admin-nrpti/src/app/home/home.component.html, angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.html, angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.spec.ts, angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts, angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts, angular/projects/common/src/app/utils/record-constants.ts, api/migrations/20201216180728-updateCoorsRecords.js, api/src/importers/coors/base-record-utils.js, api/src/importers/coors/base-record-utils.test.js, api/src/importers/coors/datasource.js, api/src/importers/coors/datasource.test.js, api/src/importers/coors/tickets-utils.js, api/src/importers/coors/tickets-utils.test.js, api/src/importers/coors/utils/csv-utils.js, api/src/importers/coors/utils/csv-utils.test.js, api/src/swagger/swagger.yaml, api/src/tasks/import-task.js, api/src/utils/constants/misc.js
https://bcmines.atlassian.net/browse/NRPT-222
* Renamed CORS to COORS (coors-csv, _sourceRefCoorsId, etc...)
* Set COORS record author to equal issuing agency
* Set COORS record name to equal to offence
* Set dateOfBirth to current date for individuals without names.  This causes NRCED to display "Unpublished" for names
* Migrations to fix existing records
=> NRPT-222 Update COORS records and importer

angular/projects/public-lng/src/app/explore-panel/explore-panel.component.html, angular/projects/public-lng/src/app/project/authorizations/authorizations.component.ts, angular/projects/public-lng/src/app/project/compliance/compliance.component.ts, angular/projects/public-lng/src/app/project/plans/plans.component.ts
https://bcmines.atlassian.net/browse/NRPT-603
Fixing LNG agency and author filters not working properly
=> NRPT-603 Fix LNG Agency and Author filters

angular/projects/admin-nrpti/src/app/home/home.component.html, angular/projects/admin-nrpti/src/app/home/home.component.spec.ts, angular/projects/admin-nrpti/src/app/home/home.component.ts, angular/projects/admin-nrpti/src/app/records/records-rows/records-table-row.component.html, angular/projects/admin-nrpti/src/app/records/records-rows/records-table-row.component.ts, angular/projects/admin-nrpti/src/app/services/factory.service.ts
[NRPT-625](https://bcmines.atlassian.net/browse/NRPT-625)
=> NRPT-625: disable record edit in table rows based on role, hide import card

angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.ts, angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts, angular/projects/common/src/app/document-edit/document-edit.component.html, angular/projects/common/src/app/document-edit/document-edit.component.ts, angular/projects/common/src/app/document-link-staging/document-link-staging.component.html, angular/projects/common/src/app/document-link-staging/document-link-staging.component.ts, angular/projects/global/src/lib/components/date-picker/date-picker.component.html, angular/projects/global/src/lib/components/date-picker/date-picker.component.ts
- [NRPT-571](https://bcmines.atlassian.net/browse/NRPT-571)
=> NRPT-571: disable editing of record fields and documents for core records

api/src/controllers/post/administrative-penalty.js, api/src/utils/post-utils.js, api/src/utils/post-utils.test.js, api/src/utils/put-utils.js, api/src/utils/put-utils.test.js
Will address tests another time.
=> NRPT-581: public role adding/removing based on POST/PUT logic

api/src/importers/coors/tickets-utils.js, api/src/importers/coors/tickets-utils.test.js, api/src/importers/nro/inspections-utils.js, api/src/importers/nro/inspections-utils.test.js
https://bcmines.atlassian.net/browse/NRPT-635
=> NRPT-635 Fix COORS records Birth Date when individual names are imcomplete

angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.html, angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.ts, angular/projects/admin-nrpti/src/app/records/permits/permit-detail/permit-detail.component.html, angular/projects/admin-nrpti/src/app/records/permits/permit-detail/permit-detail.component.ts, angular/projects/admin-nrpti/src/app/records/records-rows/records-table-row.component.ts
[NRPT-571](https://bcmines.atlassian.net/browse/NRPT-571)
=> NRPT-571: disable core record editing in mines & record pages

angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.html, angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts, api/src/controllers/post/permit.js
- fix uneditable record name when creating new record
=> NRPT-648: fix manual permit record not saving

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.html, angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts, angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts, angular/projects/common/src/app/utils/record-constants.ts, api/src/controllers/post/inspection.js, api/src/importers/agri/base-record-utils.js, api/src/importers/agri/base-record-utils.test.js, api/src/importers/agri/datasource.js, api/src/importers/agri/datasource.test.js, api/src/importers/agri/inspection-utils.js, api/src/importers/agri/inspection-utils.test.js, api/src/models/master/inspection.js, api/src/models/nrced/inspection-nrced.js, api/src/tasks/import-task.js
[NRPT-526](https://bcmines.atlassian.net/browse/NRPT-526)
=> NRPT-526: add AGRI MIS inspections csv importer

angular/projects/common/src/app/document-link-staging/document-link-staging.component.ts, api/app.js
https://bcmines.atlassian.net/browse/NRPT-632
=> NRPT-632 Increase upload size to 25MB

api/src/importers/nro/inspections-utils.js, api/src/importers/nro/inspections-utils.test.js, api/src/importers/nro/utils/csv-utils.js, api/src/importers/nro/utils/csv-utils.test.js
https://bcmines.atlassian.net/browse/NRPT-606
Test file: https://chat.developer.gov.bc.ca/group/7yTf7q3mWbKBAn2qa?msg=JPivWJQyAGTPXph2i
Please note the test file will have some `UNKNOWN` `Client / Complainant` values.  Kyle has confirmed they are still treated as companies.  Future CSV files will not have these `UNKNOWN` rows.
=> NRPT-606: NRO Inspection - Enable publishing companies

angular/projects/common/src/app/document-link-staging/document-link-staging.component.html
https://bcmines.atlassian.net/browse/NRPT-632
Missed a default value that caused mine records still be stuck at 10MB limit
=> NRPT-632 Increase default upload size for mine records

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts, angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts, angular/projects/common/src/app/models/master/common-models/penalty.ts, angular/projects/common/src/app/utils/record-constants.ts, api/src/controllers/post/court-conviction.js, api/src/importers/coors/base-record-utils.js, api/src/importers/coors/base-record-utils.test.js, api/src/importers/coors/court-conviction-utils.js, api/src/importers/coors/court-conviction-utils.test.js, api/src/importers/coors/datasource.js, api/src/importers/coors/utils/csv-utils.js, api/src/models/master/courtConviction.js, api/src/utils/constants/misc.js, api/src/utils/constants/record-type-enum.js
[NRPT-80](https://bcmines.atlassian.net/browse/NRPT-80)
=> NRPT-80: add csv import for  coors court convictions

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts, angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts, api/src/controllers/post/administrative-sanction.js, api/src/importers/coors/admin-sacntion-utils.test.js, api/src/importers/coors/admin-sanction-utils.js, api/src/importers/coors/admin-sanction-utils.test.js, api/src/importers/coors/datasource.js, api/src/models/master/administrativeSanction.js, api/src/models/nrced/administrativeSanction-nrced.js
[NRPT-152](https://bcmines.atlassian.net/browse/NRPT-152)
=> NRPT-152: add csv import for coors administrative sanctions 

api/src/importers/coors/admin-sanction-utils.js
- [NRPT-152](https://bcmines.atlassian.net/browse/NRPT-152)
- [NRPT-505](https://bcmines.atlassian.net/browse/NRPT-505)
=> NRPT-152: fix check for AUT enforcement code in coors sanctions importer

angular/projects/common/src/app/document-link-staging/document-link-staging.component.html, angular/projects/common/src/app/document-link-staging/document-link-staging.component.ts
[NRPT-692](https://bcmines.atlassian.net/browse/NRPT-692)
Increase doc upload limit to 400mb
Can create a ~350mb and 500mb file with
`dd if=/dev/zero of=./foo.pdf bs=3m count=128`
`dd if=/dev/zero of=./fooBig.pdf bs=4m count=128`
=> increase max file upload size to 400mb

api/src/utils/s3-cleanup.js
https://bcmines.atlassian.net/browse/NRPT-305
Mainly used for the mem-admin doc backup for now
=> NRPT305: Exclude S3 objects with keys starting with 'DO_NOT_DELETE' from S3 clean up script

api/materialized_views/search/redactedRecordSubset.js, api/src/controllers/map-info-controller.js, api/src/models/index.js, api/src/models/mapLayerInfo.js, api/src/swagger/swagger.yaml, api/test/tests/controllers/map-info-controller.test.js
https://bcmines.atlassian.net/browse/NRPT-686
Test payloads:
`POST /api/map-info`
```
{
"application": "LNG",
"data": {
"location": "Nile River",
"length": "48.0 km",
"description": "paragraph of formatted text",
"segment": "Section 1"
}
}
```
`PUT /api/map-info/<id>`
```
{
"location": "Nile River",
"length": "48.0 km",
"description": "paragraph of formatted text"
}
```
`DELETE /api/map-info/<id>`
`GET /api/map-info/<id>`
`GET /api/public/map-info/<id>`
=> NRPT-686 Add Map Layer Info controller

angular/projects/public-nrpti/src/app/pipes/project-link.pipe.spec.ts, angular/projects/public-nrpti/src/app/pipes/project-link.pipe.ts, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.html, angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.html, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.spec.ts, angular/projects/public-nrpti/src/app/shared.module.ts
https://bcmines.atlassian.net/browse/NRPT-683
=> NRPT-693 Added LNG link to NRCED records

angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.html, angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.scss, angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.spec.ts, angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.scss, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.spec.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts, angular/projects/public-nrpti/src/app/records/records.module.ts, angular/projects/public-nrpti/src/app/records/utils/record-utils.ts, api/app.js, api/package-lock.json, api/package.json
https://bcmines.atlassian.net/browse/NRPT-13
- Added CSV export to NRCED.  Export button only shows if the results are being filter by keywords or the advanced filters.
- Added `compression` module to the API to enable gzip compression.  API responses for the CSV exports are around 6-8MB per request.  The `compression` module reduces these requests down to 500-700KB.
=> NRPT-13 Add NRCED CSV Export

api/src/controllers/search.js
- [NRPT-679](https://bcmines.atlassian.net/browse/NRPT-679)
=> NRPT-679: update link check for record with no documents

angular/projects/common/src/app/utils/record-constants.ts
https://bcmines.atlassian.net/browse/NRPT-741
=> NRPT-741 Add legislation description to Parks Act 9,1 Court Conviction Records

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts
https://bcmines.atlassian.net/browse/NRPT-722
=> NRPT-722 Add view/edit record buttons to collections edit

angular/package.json, angular/projects/admin-nrpti/src/app/services/toast.service.ts
Old package created a prod-only bug - swapping it out.
=> NRPT-633: Remove buggy package

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts, angular/projects/admin-nrpti/src/app/utils/constants/ams-csv-constants.ts, angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts, angular/projects/common/src/app/utils/record-constants.ts, api/migrations/20210408155320-removeAmsOrdersFromOcersCsv.js, api/src/controllers/post/order.js, api/src/importers/ams/base-record-utils.js, api/src/importers/ams/base-record-utils.test.js, api/src/importers/ams/datasource.js, api/src/importers/ams/datasource.test.js, api/src/importers/ams/orders-utils.js, api/src/importers/ams/orders-utils.test.js, api/src/models/bcmi/order-bcmi.js, api/src/models/lng/order-lng.js, api/src/models/master/order.js, api/src/models/nrced/order-nrced.js, api/src/tasks/import-task.js, api/src/utils/constants/misc.js
https://bcmines.atlassian.net/browse/NRPT-738
This PR also includes migration to remove duplicate AMS Orders from the ocers-csv source
=> NRPT-738 Add AMS Order CSV Import

angular/package-lock.json, api/src/importers/alc/inspections-utils.js
=> NRPT-716: added lat/long to alc importer

api/materialized_views/search/redactedRecordSubset.js, api/migrations/20210414200921-addPublicToOcersCsv.js
https://bcmines.atlassian.net/browse/NRPT-744
* Migration to add `public` to all ocers-csv records where the individual names are not empty
*  Exclude ocers-csv records from birthdate redaction
=> NRPT-744 Fix OCERS-CSV Issued To

api/src/utils/constants/misc.js
https://bcmines.atlassian.net/browse/NRPT-760
=> NRPT-760 Exclude AgreementLNG from redaction

api/src/utils/constants/csv/flnro-inspections-csv.js, api/src/utils/csv-helper.test.js, api/src/utils/csv-helpers.js
Addresses timezone information not being stored with record dates
=> NRPT-733: ensure timezone is set on date fields during fme imports

api/openshift/cron-materialized-views.yaml
Importer cronjob runs nightly, while the materialized views run every 30 minutes. Template has been out of date for the last while.
=> NOBUG: split nrpti cron into separate jobs for importers and views

api/src/controllers/post/court-conviction.js
This PR fixes mineGuid and unlisted mine name not being set on CourtConvictionBCMI
=> NOBUG: Fix mineGuid in CourtConviction BCMI Post

angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-add-edit/mines-administrative-penalty-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-detail/mines-administrative-penalty-detail.component.html, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-detail/mines-administrative-penalty-detail.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.html, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.ts, angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts, angular/projects/common/src/app/models/bcmi/administrative-penalty-bcmi.ts, angular/projects/common/src/app/models/bcmi/court-conviction-bcmi.ts, angular/projects/common/src/app/models/master/administrative-penalty.ts, angular/projects/common/src/app/models/master/court-conviction.ts, angular/projects/common/src/app/record-association/record-association-edit.component.html, angular/projects/common/src/app/record-association/record-association-edit.component.spec.ts, angular/projects/common/src/app/record-association/record-association-edit.component.ts, api/src/controllers/post/administrative-penalty.js, api/src/controllers/post/court-conviction.js, api/src/models/bcmi/administrativePenalty-bcmi.js, api/src/models/bcmi/courtConviction-bcmi.js, api/src/models/master/administrativePenalty.js, api/src/models/master/courtConviction.js
* allow mine type entry for unlisted mines, and autofill location
[NRPT-729](https://bcmines.atlassian.net/browse/NRPT-729)
=> NRPT-729: set mine lat-lon on selection, set default contravention

api/src/integrations/nris-epd/datasource.js
https://bcmines.atlassian.net/browse/NRPT-328
This PR also includes fix to the NRIS filename bug in https://bcmines.atlassian.net/browse/NRPT-776.  Migration for data will follow in another PR.
=> NRPT-382 Display more EPD NRIS data

angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.html
Adding issuedTo section to the Mines Court Conviction details page
=> NOBUG: Add missing issuedTo to Mines CC detail

api/src/integrations/nris-epd/datasource.js
https://bcmines.atlassian.net/browse/NRPT-328
Add additional client number to map to LNG, also use client number instead of client id
=> NRPT-328 Fix client number and add PA6006

api/migrations/20210714165516-fixNrisDocsFilenames.js
https://bcmines.atlassian.net/browse/NRPT-776
=> NRPT-776 Fix NRIS doc filenames

angular/projects/public-nrpti/src/app/records/records-list/records-list.component.spec.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts, angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.html, angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.spec.ts, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.html, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.scss, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.ts, angular/projects/public-nrpti/src/app/records/records.module.ts, angular/projects/public-nrpti/src/app/records/share-record-button/share-record-button.component.html, angular/projects/public-nrpti/src/app/records/share-record-button/share-record-button.component.scss, angular/projects/public-nrpti/src/app/records/share-record-button/share-record-button.component.spec.ts, angular/projects/public-nrpti/src/app/records/share-record-button/share-record-button.component.ts
https://bcmines.atlassian.net/browse/NRPT-775
=> NRPT-775 Add share button to NRCED

api/migrations/20210728213257-remove-G-4-352-permits.js, api/src/integrations/core/datasource.js
https://bcmines.atlassian.net/browse/NRPT-684
=> NRPT-84 Use M-215 for Lumby Mine

angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.html
https://bcmines.atlassian.net/browse/NRPT-803
=> NRPT-803 Add heading to Url/Text on BCMI Court Conviction

angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-add-edit/mines-administrative-penalty-add-edit.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-add-edit/annual-report-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-add-edit/certificate-amendments-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-add-edit/construction-plan-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-add-edit/dam-safety-inspection-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts, angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
https://bcmines.atlassian.net/browse/NRPT-799
=> NRPT-799 Fix location centroid saving as null,null

api/src/integrations/nris-epd/datasource.js
https://bcmines.atlassian.net/browse/NRPT-810
=> NRPT-810 Use different date for GGIRCA records

angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts
https://bcmines.atlassian.net/browse/NRPT-811
=> NRPT-811 Change COORS Ticket TICKET_DATE format

angular/projects/admin-nrpti/src/app/import/import.component.html, angular/projects/public-nrpti/src/app/app.component.ts, angular/projects/public-nrpti/src/app/pipes/project-link.pipe.spec.ts, angular/projects/public-nrpti/src/app/pipes/project-link.pipe.ts, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.spec.ts, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.spec.ts, angular/projects/public-nrpti/src/app/services/factory.service.ts, api/migrations/20210812165533-removeOldEmliRecords.js, api/migrations/20210816170601-addApplicationUrls.js, api/src/controllers/config.js, api/src/integrations/nris-emli/datasource.js, api/src/integrations/nris-emli/datasource.test.js
https://bcmines.atlassian.net/browse/NRPT-777
=> NRPT-777 Update NRIS-EMLI Importer

api/src/importers/coors/court-conviction-utils.js
Small fixes to import columns when Tickets are imported as Court Convictions
https://bcmines.atlassian.net/browse/NRPT-798
https://bcmines.atlassian.net/browse/NRPT-811
=> NRPT-798 NRPT-811 Fixes

angular/projects/common/src/app/legislation/legislation-list-detail-public/legislation-list-detail.component.html, angular/projects/common/src/app/legislation/legislation-list-detail-public/legislation-list-detail.component.scss, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.scss, angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.ts, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html, angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.scss, angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.html, angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.scss, angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.ts, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html, angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.scss, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.html, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.scss, angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.html, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.scss, angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.ts, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.scss, angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.ts, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.scss, angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.ts, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.scss, angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.spec.ts
NRPT-809 populate description field in collapsed row
NRPT-788 changes to card layouts, warnings added
NRPT-809 moving outcome description field
NRPT-788 and NRPT-809
https://bcmines.atlassian.net/browse/NRPT-788
https://bcmines.atlassian.net/browse/NRPT-809
=> NRPT-788 and NRPT-809

api/src/importers/coors/court-conviction-utils.js, api/src/integrations/nris-emli/datasource.js
=> NRPT-777 Capitalize status description

angular/projects/admin-nrpti/src/index.html, angular/projects/public-lng/src/index.html, angular/projects/public-nrpti/src/app/records/utils/record-utils.ts, angular/projects/public-nrpti/src/index.html
Changelog:
- Changed legislationDescription to Summary
- Updated code for snow plow (the current code is intended for dev and test only))
=> Export CSV Fixes

angular/projects/admin-nrpti/src/app/utils/constants/misc.ts, angular/projects/common/src/app/utils/record-constants.ts, angular/projects/global/src/lib/utils/utils.ts, api/src/importers/ams/orders-utils.js, api/src/importers/ams/orders-utils.test.js, api/src/importers/cmdb/inspection-utils.js, api/src/importers/cmdb/inspection-utils.test.js, api/src/importers/coors/admin-sanction-utils.js, api/src/importers/coors/admin-sanction-utils.test.js, api/src/importers/mis/inspection-utils.js, api/src/importers/mis/inspection-utils.test.js, api/src/integrations/nris-epd/datasource.js, api/src/utils/constants/misc.js, api/test/factories/order-factory.js
Changelog:
- Ministry of FLNR -> Ministry of Forests
- Ministry of Agriculture Food and Fisheries -> Ministry of Agriculture and Food
- Environmental Protection Division -> Ministry of Environment and Climate Change Strategy
=> Changed the ministry names to the udpated ones

angular/projects/public-lng/src/app/home/home.component.html
Text change to the alert banner on LNG homepage
=> Text change to the homepage notice for LNG

api/src/utils/constants/misc.js
Changelog:
* Fix issuingAgency constants; correctly changes Water Sustainability Act and revert BC Energy Regulator / Conservation Officer Service change
=> fix prev change for issuingAgency

angular/projects/public-lng/src/app/contact/contact.component.html, angular/projects/public-lng/src/app/faq/faq.component.html, angular/projects/public-lng/src/app/home/home.component.html, angular/projects/public-lng/src/assets/data/general/home.json, angular/projects/public-lng/src/assets/data/project1/authorizations.json, angular/projects/public-lng/src/assets/data/project1/compliance.json, angular/projects/public-lng/src/assets/data/project2/authorizations.json, angular/projects/public-lng/src/assets/data/project2/compliance.json, angular/projects/public-lng/src/assets/data/project2/overview.json, angular/projects/public-lng/src/assets/data/project2/plans.json, angular/projects/public-nrpti/src/app/home/home.component.html, api/src/integrations/bcogc/datasource.js, api/src/integrations/bcogc/warnings-utils.test.js
Changelog:
* Update references from BC Oil and Gas Commission to BC Energy Regulator 
* Update wording around BC Energy Regulator change
* Fix links to new website
=> 1073 nrced about page update

.github/PULL_REQUEST_TEMPLATE.md, .github/labeller.yaml, .github/workflows/pr-labeller.yaml
- Added Labeller Script and Action to tag new Pull Requests
- Added Template to populate new PR's for ease of communication and keeping standards
=> [NRPTI-N/A] FEATURE** added Labeller action and PR template

api/src/importers/coors/court-conviction-utils.js, api/src/importers/coors/court-conviction-utils.test.js
- Added summary to GTYJ enforcement outcome logic
- Updated test
=> [NRPTI-1113] FEAT: Add summary to GTYJ enforcement outcome imports

api/src/importers/coors/court-conviction-utils.test.js, api/src/utils/constants/misc.js
- Update the AUTHORIZED_PUBLISH_AGENCIES to use the agency codes instead of name
- updated test to pass with previous updates.
=> [NRPTI-1045] FIX** update Authorized Publish Agencies / Fix Tests

angular/projects/admin-nrpti/src/app/home/home.component.ts, angular/projects/global/src/lib/utils/agency-data-service-nrced.ts, angular/projects/public-nrpti/src/app/home/home.component.html, angular/projects/public-nrpti/src/app/home/home.component.spec.ts, angular/projects/public-nrpti/src/app/home/home.component.ts
- Add agencyDataService to home components.
- Update homepage to pull agencies names from agency code in frontend.
- general code cleanup highlighted by Sonarcloud / ESLint.
=> [NRPTI-1138] HOTFIX** Update NRCED homepage to new agency codes

api/src/controllers/collection-controller.js, api/src/controllers/post/inspection.js, api/src/controllers/search.js, api/src/importers/coors/court-conviction-utils.js
- Removed the optional chaining expressions because of conflict with node version in build process
=> [NRPTI-1142] HOTFIX** Revert optional chaining due to old version of node

angular/projects/common/src/app/utils/record-constants.ts, angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.html, angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.ts
- agencypicklist references and hidden ui element removed
- linting
=> [CHORE]/[NRPTI-1158]

angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions-resolver.ts, angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts, angular/projects/common/src/app/utils/record-constants.ts
- Enforcement actions resolver and component updated to use agency code
=> [BUGFIX][NRPTI-1163] - Enforcement Actions Issue Fix

angular/projects/admin-nrpti/src/app/agencies/agencies.component.spec.ts
- Added Unit tests for Agency update page
=> [TECH-DEBT][NRPTI-1167] Agency Update Angular Test

api/src/importers/alc/base-record-utils.test.js, api/src/importers/alc/datasource.test.js, api/src/importers/ams/datasource.test.js, api/src/importers/cmdb/datasource.test.js, api/src/importers/coors/base-record-utils.test.js, api/src/importers/coors/datasource.test.js, api/src/importers/era/datasource.test.js, api/src/importers/flnr/datasource.test.js, api/src/importers/mis/datasource.test.js
- Add additional testing to the following importers and their files: alc, ams, cmdb, coors, era, flnr, mis.
- Unit tests and integration tests, ensuring functionality is properly outlined and retrieved as expected
```
| File Name                   | Old Coverage | New Coverage | Improvement |
|-----------------------------|--------------|--------------|-------------|
| importers/alc               | 65.89%       | 84.5%        | +18.61%     |
| importers/ams               | 72.52%       | 90.08%       | +17.56%     |
| importers/cmdb              | 65.32%       | 86.29%       | +20.97%     |
| importers/coors             | 73.97%       | 94.63%       | +20.66%     |
| importers/era               | 72.5%        | 91.67%       | +19.17% …
```
=> [TECH-DEBT][NRPTI-1167]** Imports test coverage improvements

api/src/integrations/bcogc/administrative-penalties-utils.test.js, api/src/integrations/bcogc/bcogc-utils-types-enum.test.js, api/src/integrations/bcogc/datasource.test.js, api/src/integrations/bcogc/orders-utils.test.js, api/src/integrations/bcogc/warnings-utils.test.js
- Add additional testing to the integrations for BCOGC
- Create tests for the following:
- administrative-penalties-utils.js
- orders-utils.js
| File Name                           | Old Coverage | New Coverage | Improvement   |
|-------------------------------------|--------------|--------------|---------------|
| integrations/bcogc  (all tests)                               | 44.41%        | 86.02% |  +41.61%
| --bcogc/administrative-penalties-utils.js   | 0%           | 70.5%        | +70.5% |
| --bcogc/base-record-utils.js                 | 86.05%       | 90.7%        | +4.65%        |
| --bcogc/bcogc-utils-types-enum.js           | 42.86%       | 100%         | +57.14%      |
| --bcogc/datasource.js                        | 40.86% …
=> [TECH DEBT][NRPTI-1167] - additional testing for BCOGC integration

api/src/integrations/core-documents/datasource.test.js, api/src/integrations/core/collection-utils.test.js, api/src/integrations/core/datasource.test.js, api/src/integrations/core/mine-utils.test.js, api/src/integrations/core/permit-utils.test.js
- Add additional testing for the CORE integration (and CORE-documents)
| File                         | Old Coverage | New Coverage | Improvement |
|------------------------------|--------------|--------------|-------------|
| *integrations/core (all files)* | 37.74%        | **63.21%**        | +25.47%      |
| --base-record-utils.js         | 81.82%        | **87.88%**        | +6.06%       |
| --collection-utils.js          | 20.83%        | **91.67%**        | +70.84%      |
| --datasource.js                | 31.66%        | **44.72%**        | +13.06%      |
| --mine-utils.js                | 66.67%        | **96.97%**        | +30.3%       |
| --permit-utils.js              | 10.34%        | **100%**          | +89.66%      |
| …
=> [TECH-DEBT][NRPTI-1167]** add additional testing for CORE integration

api/package.json, api/src/integrations/nris-emli/datasource.test.js, api/src/integrations/nris-epd/datasource.test.js, api/test/setEnvVars.js
- add additional testing to datasource.js for nris-emli integration
- add testing to datasource.js for nris-epd integration
- add fake environmental variables for Jest to use for additional testing
| File                                                              | Old Coverage | New Coverage | Improvement |
|----------------------------------------|--------------|--------------|-------------|
| *integrations/nris-emli*                           | 28.9%             | **81.19%**        | +52.29%      |
| --datasource                                            | 28.9%          | **81.19%**        | +52.29%       |
| *integrations/nris-epd*                          | 27.05%               | **78.69%**        | +51.64%      |
| --datasource …
=> [TECH-DEBT][NRPTI-1167]** add additional testing for NRIS integrations

angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.ts, angular/projects/public-nrpti/src/app/records/utils/record-utils.spec.ts, angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
- Fix to the export function on NRCED to change an agency from its code to the correct name
- Update to the export test
=> [BUGFIX][NRPTI-1173]** Fix CSV export bug to reference the correct agency name

tools/metabase/metabase.dc.yaml
=> [TECH-DEBT]/[NRPTI-1052] - Metabase Update

angular/projects/admin-nrpti/src/app/agencies/agencies.component.ts, angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions.component.html, angular/projects/admin-nrpti/src/app/header/header.component.html, angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-add-edit/mines-administrative-penalty-add-edit.component.html, angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.ts, angular/projects/common/src/app/link-add-edit/link-add-edit.component.html, angular/projects/public-nrpti/src/app/header/header.component.html, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html, angular/projects/public-nrpti/src/index.html, api/database.json-sample, api/migrations/README.md
- Minor typo fixes to HTML pages to have consistent titles and formatting; several other typos found and fixed.
- Clarified steps for setting up and running migrations locally with the Docker container vs. without Docker; updated README and `database.json-sample file`
=> [TASK][NRPTI-#1185] Fix Typos in HTML. Update Migration README and database.json-sample files.

angular/projects/admin-nrpti/src/app/mines/mines-collections-list-resolver.ts, api/src/controllers/metric.js, api/src/integrations/core/datasource.js
- Updates Collection and permits if the 'public' read permission doesn't match between them
- Create and update collections for all permits not just verified permit
- Various null bug fixes
=> [BUG][NRPTI-1242] Update permits if permissions don't match collection

api/src/controllers/search.js, api/src/integrations/nris-emli/datasource.js, api/src/integrations/nris-emli/datasource.test.js
- Update assessment Sub Types
- Update test cases
- Remove Inspection attachment logic and test cases temporarily
=> [HOTFIX][NRPTI-1264] Update assessment sub types

angular/Dockerfile, angular/Dockerfile-public-nrpti, angular/entrypoint-public-nrpti.sh, angular/entrypoint.sh, angular/projects/admin-nrpti/src/app/services/keycloak.service.ts, docker-compose.yaml
- updated frontend to use Docker.
- s/o to Ariel 💯
=> CI: updated Docker to work with Keycloak

.github/workflows/deploy.yml, .github/workflows/pr-open.yml, angular/package-lock.json, tools/angular-builder/angular-builder.bc.yaml, tools/api/api.bc.yaml
=> ci: added webhook trigger

angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
=> feat: added csv feature for testing

tools/angular-on-nginx/admin-nrced.dc.yaml, tools/angular-on-nginx/public-nrced.dc.yaml, tools/api/api.dc.yaml
=> ci: reset to deployconfig

angular/projects/public-nrpti/src/app/records/records-list/export-csv/export-csv.component.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html, angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts, angular/projects/public-nrpti/src/app/records/utils/record-utils.ts, angular/projects/public-nrpti/src/app/services/factory.service.ts
=> fix: logging to see export issue

angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
=> fix: Test to fix export

angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
=> chore: Remove comments used for debugging

angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
=> Commented out export

api/openshift/cron-materialized-views.yaml
- Update materialized views cronjob to use client credentials auth flow
- Remove keycloak username and password
- Update  materialized views cronjob base container image
=> Missing Metabase records.

api/src/controllers/search.js
=> Update redaction logic

api/Dockerfile
=> chore(ci): Update api dockerfile to use npm instead of yarn.

angular/package.json
=> [FIX][NRPTI-1351] Move npm run all from dev dep to dep.

angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-detail/mines-administrative-penalty-detail.component.ts, angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.ts, angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.ts, angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.ts, angular/projects/admin-nrpti/src/app/records/agreements/agreement-detail/agreement-detail.component.ts, angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-detail/annual-report-detail.component.ts, angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-detail/certificate-amendments-detail.component.ts, angular/projects/admin-nrpti/src/app/records/certificates/certificate-detail/certificate-detail.component.ts, angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-detail/construction-plan-detail.component.ts, angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-detail/correspondence-detail.component.ts, angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.ts, angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-detail/dam-safety-inspection-detail.component.ts, angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.ts, angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-detail/management-plan-detail.component.ts, angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.ts, angular/projects/admin-nrpti/src/app/records/permits/permit-detail/permit-detail.component.ts, angular/projects/admin-nrpti/src/app/records/reports/report-detail/report-detail.component.ts, angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.ts, angular/projects/admin-nrpti/src/app/records/self-reports/self-report-detail/self-report-detail.component.ts, angular/projects/admin-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.ts, angular/projects/admin-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.ts
=> [FIX][NRPTI-1351] Add duplicated fix to test record data display.
