bcgov/NRPTI

angular/projects/admin-nrpti/src/app/import/import.component.ts
angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
api/src/controllers/search.js

Add more error handling to list pages for when results are empty.
Was checking out the new mongo stuff, but noticed we were getting a circular json stringify error.  Investigated and it looks like the mongo aggregate by default returns the entire cursor.  But slapping on .toArray() gives just the results.

PTI-81-2: Add .toArray() call to mongodb aggregate cursor result.

---

api/.eslintignore
api/.prettierignore
api/package.json
api/src/integrations/epic/epic-datasource.js
api/src/integrations/epic/epic-datasource.test.js
api/src/integrations/epic/epic-inspections.js
api/src/integrations/epic/epic-inspections.test.js
api/src/integrations/epic/epic-orders.js
api/src/integrations/epic/epic-orders.test.js
api/src/integrations/integration-utils.test.js
api/src/utils/query-actions.test.js

- All api unit tests passing.
- Updated epic import to move the project fetching into epic-datasource (out of the type specific utils).
- Partially because I think it fits better there, and partially because it makes the testing easier.
- Added better lint commands to package.json:
- It now has both non-fix and fix versions, with updated config.
- Added the migrations, and other similar folders, to the lint ignore.

PTI-329: update epic import, fix unit tests, add/fix lint commands.

---

angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.ts
angular/projects/admin-nrpti/src/app/records/inspections/inspection-resolver.ts
angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-resolver.ts
api/src/swagger/swagger.yaml

Update to leverage the addition of populate, added here: https://github.com/bcgov/NRPTI/pull/109
I also updated the swagger search order enum. I removed some values that aren't used anywhere, and added the one being used in the admin records-list page.
But, the list page seemed to be sorting just fine before I changed it, so I'm not sure what the swagger is actually enforcing.

PTI-258-2: Update admin details to leverage new getItem populate.

---

angular/projects/admin-nrpti/src/app/import/import.component.ts

When I originally removed the URL column, I didn't adjust the remaining column sizes to compensate, and so the header cols didn't quite line up with the body cols.

PTI-342: Update imports table columns.

---

api/src/integrations/epic/epic-inspections.js
api/src/integrations/epic/epic-orders.js

Had a meeting with EAO to figure this out. Turns out documentDate is a legacy field from middle EPIC. Their migration script was supposed to convert all documentDates over to datePosted. It seems to have failed and there is currently a ticket submitted for them to fix this issue. DatePosted is supposed to be the field we use to map to our dateIssued. However, EAO is unsure if even datePosted is correct for this mapping. Also, there are several issues with their datePosted field. Some new records such as their new Site C documents will have a datePosted of 1900. Also, some records will simply not have the datePosted field for whatever reason.
As of 2020-01-27, our importer will use datePosted as dateIssued. However, for some records, this field will remain blank or may be wrong. This will …

PTI-344: Setting EPIC datePosted to map to NRPTI dateIssued

---

angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html
angular/projects/admin-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.html
angular/projects/admin-nrpti/src/app/records/orders/order-detail/order-detail.component.ts
angular/projects/common/src/app/models/master/inspection.ts
angular/projects/common/src/app/models/master/order.ts
api/migrations/20200109220142-projectData.js
api/src/integrations/epic/epic-inspections.js
api/src/integrations/epic/epic-orders.js
api/src/models/master/agreement.js
api/src/models/master/authorization.js
api/src/models/master/inspection.js
api/src/models/master/order.js
api/src/models/master/plan.js
api/src/models/master/selfReport.js
api/src/models/master/warningLetter.js
api/src/utils/query-utils.js

EPIC documents are now handled a little differently. Instead, a hot link will be created to the EPIC API to fetch documents. Also, within our records a new field has been created called attachments. Attachments is an array of objects which hold data that is required to fetch a document.
The array is as follows:
[{
url: ‘https://projects.eao.gov.bc.ca/api/document/58869414eed3c0016f85526e/fetch/Red%20Mountain%20Project%20-%201996%20Project%20Development%20Review%20Report%20contents%20include%20Purpose%20of%20Report%2C%20Introduction%20%28Background%20%26%20History%29%2C%20Geology%20%26%20Mineralization%2C%20Physiography%2C%20Environmental%20Setting%2C%20Native%20Land%20Use%2C%20Land%20Capability%20and%20Use%2C%20Socio-Economic.pdf’,
fileName: ‘Red Mountain Project - 1996 Project …

PTI-232: Enabled ability to link to imported EPIC docs

---

api/src/integrations/epic/epic-datasource.test.js
api/src/integrations/epic/epic-orders-other.js
api/src/integrations/epic/epic-record-type-enum.js

Expands the import to also fetch [type: order, milestone: other], which is persisted as [_schemaName: Order].
- _original order import was [type: order, milestone: compliance & enforcement]_

PTI-357: Add Orders import.

---

angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
angular/projects/common/src/app/models/master/certificate.ts
angular/projects/common/src/app/models/master/inspection.ts
angular/projects/common/src/app/models/master/management-plan.ts
angular/projects/common/src/app/models/master/order.ts
api/src/integrations/epic/certificates-amendment-utils.js
api/src/integrations/epic/certificates-utils.js
api/src/integrations/epic/inspections-utils.js
api/src/integrations/epic/management-plans-utils.js
api/src/integrations/epic/orders-other-utils.js
api/src/integrations/epic/orders-utils.js
api/src/models/master/certificate.js
api/src/models/master/inspection.js
api/src/models/master/managementPlan.js
api/src/models/master/order.js

Commit 1:
- Update API models and imports (for the types the import supports) to include description in the master record.
- I also added attachments support to imports that were missing it.
Commit 2:
- Update Flavour add/edit (for the types the import supports) to use the master description if the flavour record does not exist.
- I also added the attachments field to the model for a type that was missing it.

PTI-320: Add master description as default flavour description.

---

angular/projects/admin-nrpti/src/app/records/records-list/records-list.component.ts
angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts
api/src/controllers/search.js

I was playing with the admin list page, and noticed that the page still took a while to load.
Poked around at the search.js and noticed the $lookup for documents and flavours happened before the page limit step.  Moved it to after this step and now its much faster.
The only drawback is that, currently, you wouldn't be able to filter on documents or flavours, since the $lookup would need to happen earlier for that to work.  If we even need that ability, we would probably need to add some kind of check that recognized a sort on a document or flavour field, and then tack on the $lookup earlier, rather than later.
Also included 2 minor table column sorting fixes, because I happened to notice they were wrong during this testing.

PTI-411: Improve search performance + sort fix.

---

angular/projects/common/src/app/models/lng/administrative-penalty-lng.ts
angular/projects/common/src/app/models/lng/administrative-sanction-lng.ts
angular/projects/common/src/app/models/lng/agreement-lng.ts
angular/projects/common/src/app/models/lng/certificate-lng.ts
angular/projects/common/src/app/models/lng/construction-plan-lng.ts
angular/projects/common/src/app/models/lng/inspection-lng.ts
angular/projects/common/src/app/models/lng/management-plan-lng.ts
angular/projects/common/src/app/models/lng/order-lng.ts
angular/projects/common/src/app/models/lng/permit-lng.ts
angular/projects/common/src/app/models/lng/restorative-justice-lng.ts
angular/projects/common/src/app/models/lng/self-report-lng.ts
angular/projects/common/src/app/models/lng/ticket-lng.ts
angular/projects/common/src/app/models/lng/warning-lng.ts
angular/projects/common/src/app/models/master/administrative-penalty.ts
angular/projects/common/src/app/models/master/administrative-sanction.ts
angular/projects/common/src/app/models/master/inspection.ts
angular/projects/common/src/app/models/master/order.ts
angular/projects/common/src/app/models/master/restorative-justice.ts
angular/projects/common/src/app/models/master/ticket.ts
angular/projects/common/src/app/models/master/warning.ts
angular/projects/common/src/app/models/nrced/administrative-penalty-nrced.ts
angular/projects/common/src/app/models/nrced/administrative-sanction-nrced.ts
angular/projects/common/src/app/models/nrced/inspection-nrced.ts
angular/projects/common/src/app/models/nrced/order-nrced.ts
angular/projects/common/src/app/models/nrced/restorative-justice-nrced.ts
angular/projects/common/src/app/models/nrced/ticket-nrced.ts
angular/projects/common/src/app/models/nrced/warning-nrced.ts

Realized I never actually updated the angular models when I did the re-arch/schema work.
Nothing was broken before, since we still were fetching master + flavours in admin, and referencing the same fields from each.
This came to light when I was trying to make some changes for the IssuedTo PR.

PTI-411: Update common models for new arch/schemas

---

angular/projects/common/src/app/models/master/common-models/entity.ts
angular/projects/common/src/app/utils/record-constants.ts
angular/projects/global/src/lib/components/table-template/table-object.ts
angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.ts
api/migrations/20200211065122-nrcedData.js
api/src/utils/post-utils.js

Remove 'Warning' from NRCED activity type filters
Remove 'ALL' option from records-list page size
Update issuedTo display string to not show dashes, etc.
Show 'Unpublished' on NRCED if no issuedTO object exists (redacted).
Update nrced migration to not add issuedTo public role if its an anonymous person.

Remove 'Warning' from NRCED activity type filters

---

api/src/controllers/document-controller.js
api/src/controllers/record-controller.js
api/src/integrations/epic/base-record-utils.js
api/src/integrations/epic/base-record-utils.test.js
api/src/integrations/epic/datasource.js
api/src/integrations/epic/datasource.test.js
api/src/integrations/epic/epic-record-type-enum.js
api/src/integrations/epic/inspections-utils.js
api/src/integrations/epic/orders-utils.js
api/src/integrations/nris/datasource.js
api/src/tasks/import-task.js
api/src/utils/constants/record-type-enum.js

PTI-408: Refine import to only fetch some record types from LNG projects only.
- Supports the new arch/models + supports updates properly
- Tries to find an existing record
- If Found
- Transform record and call recordController.processPutRequest which has all of the logic for editing records, including their flavours
- If Not Found
- Transform record and call recordController.processPostRequest which has all of the logic for creating records, including their flavours
- Utilizes the taskAuditRecord to update counts/totals live.

PTI-470: Improve epic import to support updates + new arch/models.

---

angular/projects/common/src/app/entity/entity-add-edit/entity-add-edit.component.html

`<option (click)="stuff()">` works in firefox but is never triggered in chrome.
`<select (change)="stuff()">` works in both.
:/

PTI-584: Update entity type select event to work in Chrome

---

api/src/utils/business-logic-manager.js

Remove date portion of the check, so all NRIS-EPD records are not anonymous, regardless of date issued.

PTI-599: update nris-epd anonymous rules

---

api/migrations/20200603153526-bcmiDataLoad.js

Migration script to fetch data from the BCMI api and update matching records in NRPTI. 
We don't currently have any data from Core, so testing was done by creating some mock data with matching names (basically just copied some data in from BCMI directly and matched the schema)
Schema name is `MineBCMI` in the script, matching with [PR 338](https://github.com/bcgov/NRPTI/pull/388). This can be updated as needed! sourceSystemRef for all updated records will be set to `mem-admin` so it should be easy to wipe and rerun the migration as needed.
See ticket [NRPT-102](https://bcmines.atlassian.net/browse/NRPT-102)

NRPT-102: BCMI data update script

---

angular/projects/admin-nrpti/src/assets/styles/components/doc-list.scss
angular/projects/common/src/app/document-edit/document-edit.component.html

Long document names could stretch the screen and hide content and buttons. Added a max-width calc and overflow/ellipsis to prevent display of excessive text. As an added bonus, fixed the tooltip to show the document name, rather then `[object, object]`
See ticket [NRPT-42](https://bcmines.atlassian.net/browse/NRPT-42)

NRPT-42: Max width on link, fix tooltip

---

angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.html
angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.spec.ts
angular/projects/admin-nrpti/src/app/mines/mines-add-edit/mines-add-edit.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.html
angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.spec.ts
angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-resolver.ts
angular/projects/admin-nrpti/src/app/mines/mines-routing.module.ts
angular/projects/admin-nrpti/src/app/mines/mines-rows/mines-table-row.component.ts
angular/projects/admin-nrpti/src/app/mines/mines.module.ts
angular/projects/admin-nrpti/src/app/services/factory.service.ts
angular/projects/common/src/app/models/bcmi/index.ts
angular/projects/common/src/app/models/bcmi/mine.ts

Routing and initial screens for the Mines details. Includes edit page,  however save and delete have not been wired up yet - not part of the AC for the ticket.
Stub for unit test is in place, but didn't see the need to complete it until we know what components will be on the screens and how they'll be working.
See ticket [NRPT-123](https://bcmines.atlassian.net/browse/NRPT-123)

NRPT-123: Details/Edit Mines screen stubs

---

api/package.json

dependency that is used in some more recent API code was in the devDependencies section, when it should have been in dependencies.

NOBUG: Fix dependency import

---

api/src/controllers/search.js

Some restructuring to the search aggregation to prevent exceeding mongo memory limits.
Adding a `$project` stage after the `$match` stage to remove unecessary query data:
```
$project: {
_id: 1,
_flavourRecords: 1,
read: 1
}
```
Then repopulating with `$lookup` and `$replaceRoot` in the `$facet` stage. If populate is true, those lookups will also merge into the facet stage.
Note that `allowDiskUse` is still set to true as a safetly net for when we do exceed the size limits, but all queries should now run as expected if it is disabled.
See ticket [NRPT-169](https://bcmines.atlassian.net/browse/NRPT-169)

NRPT-169: Memory limit on MongoDB queries

---

api/src/integrations/epic/epic-record-type-enum.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-60
Updated the Epic importer to pull 2018 legislation documents. Not all 2002 document types have a corresponding 2018 type. For the ones that do this importer will now pull them in.

NRPT-60: Update Epic importer for 2018 legislation

---

angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.html

Kit and I both submitted PRs recently that touched the add-edit components for the same record types.  My PR moved the recordName field from the lng flavour section into the master section, and Kits re-organized the lng and nrced flavour sections.
No major issues or anything resulted, we just accidentally ended up with 2 copies of the recordName field in the HTML of some of the record components.
This PR removes the duplicate recordName field from the lng section.

NOBUG: Remove recordName field from LNG flavour section

---

api/app.js
api/src/integrations/core/datasource.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-233
I made multiple changes to better import the Core records and better handle errors.
- New parameter to only import major mines (cuts down from 18,000 to ~110 records)
- Makes subsequent API calls to get more details about each record to only send 2 at a time (fixes 504 errors)
- If there are any API failures or if a record doesn't contain valid data the Mine ID is logged but the other records continue to process
When running against prod data there are 14 records that will throw errors. These are data related and are to be expected right now.

NRPT-233: Updates Core importer for better error handling

---

api/src/controllers/search.js

It was possible to float documents/flavours out of the API when a user lacked the required roles due to the redaction occurring before the population of documents. An additional redaction step has been added to the document and flavour populate to re-redact these if the user does not have the roles.
I've left the original redaction pipe in place where it is, just to preemptively strip out records we don't need to process, and keep behaviour consistent when populate=false.
See ticket [NRPT-62](https://bcmines.atlassian.net/browse/NRPT-62)

NRPT-62: Remove fullRecord, redact after doc/flavour import

---

api/src/integrations/core/datasource.js

Swap reversed Latitude and Longitude values in our Core mine importer
See ticket [NRPT-247](https://bcmines.atlassian.net/browse/NRPT-247)

NRPT-247: Swap around LatLong on Core mine import

---

api/src/controllers/search.js

Strings that equal 12 chars will be detected as an ObjectID, even though they're not supposed to (ie. Wildlife Act). This will cause filters to fail as it will convert the valid string into an invalid objectID.
See ticket [NRPT-274](https://bcmines.atlassian.net/browse/NRPT-274)
Note: I believe the fix requested in the ticket is incorrect. These values should remain as strings. However as some are exactly 12 chars they fail on filters as they are converted to ObjectID's inadvertently.
If the decision is made that these should all be objectid values, this fix should still be put in place as it corrects a deficiency in the ObjectID.isValid() test.

NRPT-274: Extra valid test for ObjectID type

---

angular/projects/admin-nrpti/src/app/app-routing.module.ts
angular/projects/admin-nrpti/src/app/mines/mines-collections-list-resolver.ts
angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.html
angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts
angular/projects/common/src/app/search-filter-template/search-filter-template.component.ts
api/src/controllers/search.js
api/src/models/bcmi/collection-bcmi.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-200
Uses the new search component to add searching to the collections list of a mine.
Three of the ticket criteria are currently not implemented. Agency and Type have placeholders in the code and can be implemented once this is known from the create collection ticket. Searching on BCMI tab is currently not possible. Again, will have to wait to see how collection creation is implemented.

NRPT-240: Adds collection search

---

angular/projects/admin-nrpti/src/app/mines/mines-records-list-resolver.ts
angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.html
angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.ts

Adding the mines records list filters, updating resolver. Note that some filters are not yet implementable: BCMI Published and Has Collection. These will have to be implemented once their requisite components are in place in the system.
Second part of ticket [NRPT-199](https://bcmines.atlassian.net/browse/NRPT-199)

NRPT-199: Add in Mine Record List filter set

---

api/src/controllers/post/permit-amendment.js
api/src/integrations/core/mine-utils.js
api/src/integrations/core/mine-utils.test.js
api/src/integrations/core/permit-amendment-utils.js
api/src/models/bcmi/permitAmendment-bcmi.js
api/src/models/master/permitAmendment.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-252
There were a couple issues that would occur when the Core import would run an update on a Mine record. One problem is that using the put-utils, anything named 'documents' goes through a role update, but they expect it to just be an array of object IDs. Permit Amendment documents are a different shape, so I update the property to reflect that and avoid the role update which should not happen on them.

NRPT-252: Fixes Core Import Update

---

angular/projects/admin-nrpti/src/app/mines/mines-records-list-resolver.spec.ts
angular/projects/admin-nrpti/src/app/mines/mines-records-list-resolver.ts
angular/projects/admin-nrpti/src/app/mines/mines-routing.module.ts
angular/projects/common/src/app/utils/record-constants.ts

Adding filter to resolver to return only records asssociated with a mine via their mineGuid
See ticket [NRPT-282](https://bcmines.atlassian.net/browse/NRPT-282)

NRPT-282: Adding mineGuid to 'and' in list resolver

---

angular/projects/common/src/app/autocomplete-multi-select/autocomplete-multi-select.component.html
angular/projects/common/src/app/autocomplete-multi-select/autocomplete-multi-select.component.ts

There's an outstanding bug in the angular material autocomplete component that can cause the panel to not display in some circumstances if the component has the focus. This is mainly around mat-option click events and the "clear selected" functionality.
To get around this, I've added the MatAutocompleteTrigger to force an onChange event whenever the clear is selected, which will force the popup to display as expected.
Additionally, fixed a small bug where you couldn't hit the "clear selected" option via keyboard commands only.

NRPT-167: Fix for panel display on focus bug

---

api/migrations/20200724171605-bcmiDataLoad.js

We will need to delete the bcmiDataLoad migration from the DBs before re-running this.  It's safe to do so as this script can be run as many times as necessary.

NRPT-249: Update mine map for populating summary with Intro content.

---

angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/agreements/agreement-add-edit/agreement-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-add-edit/annual-report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-add-edit/certificate-amendments-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-add-edit/construction-plan-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-add-edit/dam-safety-inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts

Disables the edit form controls on record editing for all imported record (any record where the sourceSystemRef is not "nrpti"). Flavours are not affected. Many record edit screens also allowed editing the record name if you had appropriate NRCED, LNG, and BCMI admin access, so those follow the same rules.
See ticket [NRPT-190](https://bcmines.atlassian.net/browse/NRPT-190)

NRPT-190: Disable edit for imported records

---

angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/agreements/agreement-add-edit/agreement-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-add-edit/annual-report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-add-edit/certificate-amendments-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-add-edit/construction-plan-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-add-edit/dam-safety-inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
angular/projects/common/src/app/models/bcmi/index.ts
api/src/controllers/document-controller.js
api/src/controllers/record-controller.js
api/src/utils/business-logic-manager.js
api/src/utils/business-logic-manager.test.js

Changes to allow documents to be published on the creation of a new record, when a record is published, or when a document is updated. Additionally, a couple of other small fixes to issued identified while fixing the core issue.
Updated the businessLogicManager `isDocumentConsideredAnonymous` function so a new record without documents or a record that does not have an `issuedTo` attribute could be public. Previously the only documents that could ever be published had a very thin criteria that expected some values that would not be consistent with all record types.
Also added a step when publishing a record to go through and publish any associated docs. This will call the `isDocumentConsideredAnonymous` function as well, for consistency and to prevent publishing a document that should not …

NRPT-319: Document publish fixes

---

api/migrations/20200807181534-fixMineGuidDefault.js
api/migrations/20200810162152-fixNrisSourceRef.js
api/src/controllers/post/inspection.js
api/src/integrations/nris-epd/datasource.js
api/src/models/bcmi/permit-bcmi.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-57
Stops duplication when the NRIS importer is run more than once. Also includes a migration to add the source reference ID for the NRIS records as there was an issue that was saving them as `null`.

NRPT-57: Allows multiple NRIS imports

---

angular/projects/admin-nrpti/src/typings.d.ts

Update to roles constants made the import come from the api JS package, which is causing typescript build errors in the common libraries due to missing type. Added a typedef to get our builds working.

NOBUG: Declare type for ApplicationRoles

---

api/src/integrations/epic/inspections-utils.js
api/src/integrations/epic/orders-utils.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-219
Changes: Updates the EPIC importer to address a data discrepancy in EPIC where the `company` field might not be filled in.  If the field is missing it will now fall back to the organization's name which is required.

NRPT-219: Fixes EPIC importer for company name

---

angular/projects/admin-nrpti/src/app/services/factory.service.ts
angular/projects/admin-nrpti/src/app/services/keycloak.service.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
angular/projects/admin-nrpti/src/typings.d.ts

Nuclear option, just to get the builds working. Putting the constants back in place on the common lib and removing the failing reference to the API package.

NOBUG: Re-implement common constants

---

angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.html
angular/projects/admin-nrpti/src/app/mines/mines-collections-list/mines-collections-list.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-detail/mines-detail.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.html
angular/projects/admin-nrpti/src/app/mines/mines-records-list/mines-records-list.component.ts
angular/projects/admin-nrpti/src/app/sidebar/sidebar.component.html
angular/projects/admin-nrpti/src/app/sidebar/sidebar.component.scss
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts

Updates to split the Mines left-nav into a "Records" and "Collections" menu. Removed tabs from components. Updated the styling of the left-nav to make it more obvious it's a menu. Also, small update to replace the "Mines Details" Label of the breadcrumbs with the currently selected mine name. Note that if finding the mine name fails for whatever reason the breadcrumb will fall back to "Mine Details".
See tickets [NRPT-316](https://bcmines.atlassian.net/browse/NRPT-316), [NRPT-320](https://bcmines.atlassian.net/browse/NRPT-320) and [NRPT-321](https://bcmines.atlassian.net/browse/NRPT-321)

NRPT-316: Remove mines tabs, update breadcrumbs

---

angular/projects/admin-nrpti/src/app/mines/mines-collections-add-edit/mines-collections-add-edit.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-records-add-edit/mines-records-add-edit.component.ts
api/src/controllers/record-controller.js
api/src/controllers/search.js

Update to ensure isBcmiPublished and read role is set when records/collections are updated.
Also added a new search datatype of CollectionDocuments as a public endpoint for BCMI to use to fetch collection documents without requiring a check on the master _id values.
Additionally (and unrelated), made a fix to the hasCollection aggregate section. The hasCollection filter could cause the search to fail (and the api to crash) if you included a text search component. This is because an `$addField` step was created before the `$match: {$text}}` which mongodb does not allow in an aggregate. I've updated the logic to create the addField and match check after the main match processing is done.
See ticket [NRPT-344](https://bcmines.atlassian.net/browse/NRPT-344)

NRPT-344: Setting published, search endpoint update

---

api/src/integrations/nris-epd/datasource.js

Coordinates are swapped for some records in NRPTI/NRCED. A look at the data seemed to indicate that NRIS imported docs had the wrong coordinate order. A look in the code confirmed that indeed they did!
Optional: The values from NRIS should update with a re-import. As a safety-net though we could add a migration that runs through all records `centroid` attribute and swaps if `centroid[1] < -100` (basically, if any latitudes are less than 100, its a longitude and the order is wrong).
See ticket [NRPT-350](https://bcmines.atlassian.net/browse/NRPT-350)

NRPT-350: Update coordinate order for NRIS import

---

api/migrations/202008312408231-fixOcersRecords.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-224
Records that came over with the ocers-csv import did not set the helper flag `isNrcedPublished` on the master records. This caused published records to be ignored when using the advanced filters.  This migrations adds that flag to the master record based on the published state of the NRCED flavour record.

NRPT-224: Fix ocers-csv Published Records

---

angular/projects/admin-nrpti/src/app/import/import.component.html
angular/projects/admin-nrpti/src/app/import/import.component.ts
api/src/integrations/core/datasource.js

Tickets: 
- https://bcmines.atlassian.net/browse/NRPT-380
- https://bcmines.atlassian.net/browse/NRPT-326
This PR updates the CORE importer to exclude any many that have a recent status of abandoned. If the mine is missing a status then we still want to include it. The PR also adds a manual import button to run the CORE importer.

NRPT-380, 326: Update Core importer and add manual import

---

api/src/controllers/post/collection-bcmi.js

A literal One Character Fix.
A missing 's' on the call to loop through a collections records was causing a failure during POSTs for collections (`collection.record is not iterable`) which makes sense as the attribute doesn't exist (it's supposed to be `records`... likely the primary reason for a number of the bug tickets related to collections not saving properly... but rather than link each one as a partial fix, I'll nobug this up so we can merge it in asap and it should help with the others.

NOBUG: Fix missing 's'

---

angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.html
angular/projects/admin-nrpti/src/app/mines/mines-records-rows/mines-records-table-row.component.ts

A fix to prevent the clicking of the table cell kill propogation to the checkbox (or the checkbox click causing the click event to trigger twice).
Affects a number of different bug tickets so pushing this in as a nobug to assist with debugging the other bug tickets.

NOBUG: FIxed checkbox handler

---

angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.ts
api/migrations/20200902195621-correctLatLong.js
api/src/utils/constants/misc.js

Update for the lat long fixe with [NRPT-350](https://bcmines.atlassian.net/browse/NRPT-350). Fixed a flipped order in the mines record add screen, and added a migration to cycle through all of our records and flip the centroid values where the latitude is in [0] and the longitude is in [1] ( basicalluy`if record.centroid[1] < -90`). Not a perfect check, but should be sufficient for our data.

NRPT-350: Fix record add order, coord update migration

---

angular/projects/global/src/lib/utils/utils.ts
angular/projects/public-lng/src/app/project/authorizations/authorizations-rows/authorizations-table-rows.component.html
angular/projects/public-lng/src/app/project/authorizations/authorizations-rows/authorizations-table-rows.component.ts
angular/projects/public-lng/src/app/project/compliance/compliance-rows/compliance-table-rows.component.html
angular/projects/public-lng/src/app/project/compliance/compliance-rows/compliance-table-rows.component.ts
angular/projects/public-lng/src/app/project/plans/plans-rows/plans-table-rows.component.html
angular/projects/public-lng/src/app/project/plans/plans-rows/plans-table-rows.component.ts
angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html
angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.ts
angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.html
angular/projects/public-nrpti/src/app/records/administrative-sanctions/administrative-sanction-detail/administrative-sanction-detail.component.ts
angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.html
angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.ts
angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.html
angular/projects/public-nrpti/src/app/records/inspections/inspection-detail/inspection-detail.component.ts
angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.html
angular/projects/public-nrpti/src/app/records/orders/order-detail/order-detail.component.ts
angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.html
angular/projects/public-nrpti/src/app/records/restorative-justices/restorative-justice-detail/restorative-justice-detail.component.ts
angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.html
angular/projects/public-nrpti/src/app/records/tickets/ticket-detail/ticket-detail.component.ts
angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.html
angular/projects/public-nrpti/src/app/records/warnings/warning-detail/warning-detail.component.ts
api/migrations/20200904205029-updateAcronyms.js
api/src/utils/constants/misc.js

Adding a migration to replace all instances of "Environmental Assessment Office" with EAO and "Ministry of Energy, Mines and Petroleum Resources" with EMPR in the database.
Adding a function in Global Utils to convert the acronyms back to full strings.
Adding functions in NRCED and LNG public to use the global util to display acronyms as the full text (BCMI and NRPTI show acronyms instead).
See ticket [NRPT-366](https://bcmines.atlassian.net/browse/NRPT-366)

NRPT-366: Convert ancronyms

---

api/migrations/20200709183253-loadMemDocs.js

Small fix to the mem import migration to ensure collections date and published date are set to the collection date from mem admin.
See ticket [NRPT-376](https://bcmines.atlassian.net/browse/NRPT-376)

NRPT-376: Set collection date to collection date

---

api/src/controllers/search.js

Updating the anonymous issuedTo redaction to also include a filter for sourceSystemRef === 'nrpti'. Currently we only want to redact for nrpti recourds, however this is likely to change in the future with a more "enhanced" set of criteria.
See ticket [NRPT-299](https://bcmines.atlassian.net/browse/NRPT-299)

NRPT-299: Adding nrpti filter to anonymous redact

---

angular/projects/admin-nrpti/src/app/app-routing.module.ts
angular/projects/admin-nrpti/src/app/app.module.ts
angular/projects/admin-nrpti/src/app/communications/communications.component.html
angular/projects/admin-nrpti/src/app/communications/communications.component.scss
angular/projects/admin-nrpti/src/app/communications/communications.component.ts
angular/projects/admin-nrpti/src/app/communications/communications.module.ts
angular/projects/admin-nrpti/src/app/communications/communications.resolver.ts
angular/projects/admin-nrpti/src/app/services/factory.service.ts
angular/projects/admin-nrpti/src/app/sidebar/sidebar.component.html
angular/projects/common/src/app/models/master/common-models/communications-package.ts
angular/projects/global/src/lib/services/config.service.ts
api/src/controllers/config.js
api/src/models/communicationPackage.js
api/src/models/index.js
api/src/swagger/swagger.yaml

Addition of a new model called "CommunicationPackage" that contains details for consuming applications to display a popup or other information.
The model contains the following attributes
```
{
title: string,
description: string,
startDate: date,
endDate: date,
additionalInfo: object
}
```
Consuming applications can use title, description for the popup, start/end date for when to display. Additional Info is a future-proofing open object that should allow us to include any additional attribute information we need to pass back and forth to the application. Currently not editable by the admin screen, but it should be easy to add an ad-hoc attribute creator for that.
Updates to the config service to add `/api/config/{Application}` get and post endpoints. When calling `/api/config/BCMI` for …

NRPT-387: API and screen for communication package popup

---

angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.html
angular/projects/admin-nrpti/src/app/mines/mines-collections-rows/mines-collections-table-row.component.ts

Removed Publish/Unpublish actions from the Mines Collection list ellipsis.  These actions are no long needed due to workflow change.
https://bcmines.atlassian.net/browse/NRPT-417

NRPT-417 Remove Publish/Unpublish from ellipsis on Mines Collection page

---

api/src/controllers/collection-controller.js
api/src/controllers/record-controller.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-436
This PR changes the publish endpoint for mines. When a mine is published or unpublished the associated collections, their records and the record's documents will match the same status as the mine.  This allows the user to publish or unpublish everything at once and keeps them in sync.

NRPT-436: Publish Collections with Mine

---

api/src/controllers/search.js

Sort order is defined by a collection's records array, the mongo lookups did not preserve order. Docs should now be returned in the proper order.
- [NRPT-438](https://bcmines.atlassian.net/browse/NRPT-438)

NRPT-438: return collection docs in sort order defined by collection

---

api/migrations/20200709183253-loadMemDocs.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-479
This fixes an issue where the mem-admin migration was still using the old BCMI Permit field 'amendmentDocuments' rather than the standard 'documents' field.

NRPT-479: Fixes Permit Flavour Issue With Migration

---

api/migrations/20200709183253-loadMemDocs.js
api/src/controllers/collection-controller.js
api/src/controllers/post/permit.js
api/src/integrations/core/datasource.js
api/src/integrations/epic/base-record-utils.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-503
This changes make all collections and records brought in with the mem-admin migration default to unpublished. It also updates the Core importer to set the record and collection state based on the Mine's state.
Changes will need to be made to update the status for records and collections that are manually created. Will update in another ticket.

NRPT-503: Updates Importers To Always Unpublish

---

api/src/controllers/put/administrative-penalty.js
api/src/controllers/put/administrative-sanction.js
api/src/controllers/put/agreement.js
api/src/controllers/put/annual-report.js
api/src/controllers/put/certificate-amendment.js
api/src/controllers/put/certificate.js
api/src/controllers/put/construction-plan.js
api/src/controllers/put/correspondence.js
api/src/controllers/put/court-conviction.js
api/src/controllers/put/dam-safety-inspection.js
api/src/controllers/put/management-plan.js
api/src/controllers/put/order.js
api/src/controllers/put/permit.js
api/src/controllers/put/report.js
api/src/controllers/put/restorative-justice.js
api/src/controllers/put/self-report.js
api/src/controllers/put/ticket.js
api/src/controllers/put/warning.js
api/src/integrations/core-documents/datasource.js
api/src/utils/s3-cleanup.js

https://bcmines.atlassian.net/browse/NRPT-506
This issue was caused by Permit master record DB update operation failing.  The DB operation failure was caused by a previous change to [PutUtils.editRecordWithFlavours](https://github.com/BcGovNeal/NRPTI/commit/c0628ede3519f696810f047c387531f2ff31367b#diff-e69b25854c520ba3729e82916e80a05027f56b4eb81f364194f15311a3d989fc).  This change caused a conflict in all records' `editMaster` function because it'll try to update the master records' `_flavourIds` field using both `$set` and `$addToSet`.
This PR removes the `$addToSet` operation and uses the `$set` operation instead for updating flavour ids.

NRPT-506 Fix Core-doc importer creating duplicate documents

---

api/src/controllers/collection-controller.js

https://bcmines.atlassian.net/browse/NRPT-501
Fixed issue where removing the last record(s) from a collection will cause them not to be removed from mine correctly.

NRPT-501 Records not removed from mine after being removed from collection

---

tools/docker-images/metabase/Dockerfile

Ticket: https://bcmines.atlassian.net/browse/NRPT-488
There is an issue with timeouts for complicated or data heavy queries that was fixed in version 35. I am upgrading to the most recent version to see if the error is resolved.

NRPT-488: Upgrading Metabase

---

api/migrations/202011051807132-addMissingMineGuid.js

Ticket: https://bcmines.atlassian.net/browse/NRPT-533
Records from EPIC where missing for these two mines; however, the records were available in the All Records page.  These mines were not mapped and therefore the records were not added correctly. This migration links the orphaned records to the correct mines.

NRPT-533: Fixes Issues With EPIC Records

---

api/src/integrations/core-documents/datasource.js
api/src/integrations/core/datasource.js

https://bcmines.atlassian.net/browse/NRPT-538
Core importer was checking for new permits on existing mines based on the number of permits in the database.  This does not work if there are additional sources of permits such as mem-admin.  The permit count check has been removed and now the importer just simply compares `permit_amendment_document_guid` on the incoming data for new permits.
Also fixed Core-doc importer not reporting number of records processed.

NRPT-538 Fix  Core and Core-doc importers not bringing in new data

---

angular/projects/common/src/app/models/master/common-models/penalty.ts
api/src/integrations/bcogc/administrative-penalties-utils.js
api/src/integrations/bcogc/orders-utils.js

Ticket - none
Adding in two missing fields for orders and one for issuing agency. Also fixed a NRCED bug if a record has no penalty.

NOBUG: Small BCOGC Adjustments

---

api/src/controllers/document-controller.js
api/src/controllers/post/administrative-penalty.js
api/src/controllers/post/administrative-penalty.test.js
api/src/controllers/post/order.js
api/src/controllers/post/order.test.js
api/src/utils/auth-utils.js
api/src/utils/auth-utils.test.js
api/src/utils/constants/misc.js

https://bcmines.atlassian.net/browse/NRPT-557
This PR adds logic to inject the `admin:wf` role to `read`/`write` arrays on AMP, Order`and Document records created by wildfire users.
The UI has not been updated to allow wildfire users to create NRCED and LNG records yet, so tests will need to be done with Postman.  Alternatively you can edit `userInLngRole()` and `userInNrcedRole()` in `factory.service.ts` to make the NRCED and LNG fields editable for wildfire role.

NRPT-557 Update AMP, Order and Document controller to handle wildfire create record logic

---

api/migrations/20201215225546-fixFlavourPublishedStatus.js

https://bcmines.atlassian.net/browse/NRPT-392
This PR cycles through all master records and sets their isNrcedPublished and isLngPublished flags properly.  The original ticket is only for records from LNG-CSV and NRIS-EPD, but I see no reason not to fix all records.

NRPT-392 Fix master record isNrcedPublished and isLngPublished flags

---

api/migrations/20201215225546-fixFlavourPublishedStatus.js

https://bcmines.atlassian.net/browse/NRPT-392
Updating this migration to include master _flavourRecords fixes.  There are a number of records created by the NRIS and EPIC importer between July and September 2020 that didn't have the master records' _flavourRecords array set correctly.  The root cause seems to be resolved, this just fixes existing data.
**Note:** Make sure to delete `20201215225546-fixFlavourPublishedStatus` record from migration table after merging

NRPT-392 Fix master flavour isPublished status and _flavourRecords asscociations

---

api/migrations/20210105180728-removeDuplicateCoorsRecords.js
api/src/controllers/post/ticket.js
api/src/importers/coors/base-record-utils.js
api/src/importers/coors/tickets-utils.js
api/src/importers/coors/tickets-utils.test.js
api/src/models/master/ticket.js

https://bcmines.atlassian.net/browse/NRPT-630
This PR fixes the previous incomplete COORS importer changes.  There were several places where the change from `_sourceRefCorsId` to `_sourceRefCoorsId` were missed.  This caused the importer to create duplicates.
Migration script is included to remove these duplicates
To test:
- Load current snapshot of prod and run the migration
- Run COORS importer using test file at https://chat.pathfinder.gov.bc.ca/group/7yTf7q3mWbKBAn2qa?msg=thf7bcJ54heLJGjPr
- There should be 4431 total COORS records

NRPT-630 Fix COORS importer duplicates

---

api/src/importers/nro/inspections-utils.js
api/src/importers/nro/inspections-utils.test.js

https://bcmines.atlassian.net/browse/NRPT-606
Force remove `companyName` and `centroid` fields because the entity type can change in the CSV files.  If `companyName` and `centroid` fields are previously set because the record was a company and in the new CSV file the record is an individual then the importer should delete those fields.

NRPT-606 Unset companyName and centroid if switching from company to individual

---

api/materialized_views/search/redactedRecordSubset.js
api/materialized_views/search/redactedRecordSubset.test.js
api/src/utils/constants/misc.js
api/test/factories/factory_helper.js

https://bcmines.atlassian.net/browse/NRPT-39
To test this you'll need to trigger the `redactedRecordSubset` task via `api/task` with payload `{"taskType":"updateMaterializedView", "materializedViewSubset":"redactedRecordSubset"}`
Records that are not not from the following issuing agencies are redacted regardless of the individual's age.
```
'BC Parks',
'Climate Action Secretariat',
'Conservation Officer Service',
'EAO',
'Environmental Protection Division',
```
Also fixed a minor bug in `generateFakePerson` that's not actually generating adult person

NRPT-39  Add authorized issuing agency published record redaction

---

api/materialized_views/search/redactedRecordSubset.js
api/materialized_views/search/redactedRecordSubset.test.js
api/src/controllers/search.js

https://bcmines.atlassian.net/browse/NRPT-677
Fixed a bug in the public search aggregation where it's doing a lookup on the `nrpti` collection and causing un-redacted data to end up in the search results.
Also fixed redaction materialized view setting dateOfBirth as emtpy string instead of null.
To test this you can take a copy of the live test DB and restore it locally.  Run the redacted_records_subset materialized view task(need to do this first otherwise API will crash).  Then search for `"Test 2"` on NRCED and you should get redacted individual name in the record.  
Currently this record isn't redacted on test because of this bug.  https://nrced-f00029-test.apps.silver.devops.gov.bc.ca/records;keywords=%22Test%202%22;ms=677;currentPage=1;pageSize=25;sortBy=-dateIssued

NRPT-677 Fix public search aggregation lookup to use redacted_record_subset

---

angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts

It would be nice to enforce date formats against the source prior to ingestion instead of writing specialized logic here for this and every other csv import.

NRPT-668: Fix date handling for agris-mis csv importing.

---

api/materialized_views/search/redactedRecordSubset.js
api/materialized_views/search/redactedRecordSubset.test.js
api/src/controllers/search.js

https://bcmines.atlassian.net/browse/NRPT-39
Some tweaks to the existing public issuing agency redaction code.
- Completely removed the `issuedTo` field if issuing agency isn't authorized.  This fixes redacted name not displaying just "Unpublished" on NRCED.  See [Kyle's comment](https://bcmines.atlassian.net/browse/NRPT-39?focusedCommentId=18981)
- Unset `documents` array if issuing agency isn't authorized
- Bypassed the redaction in `search` controller if it's a public search.  The redaction in search controller isn't needed for public searches because the data is already redacted in the view.  It's also causing data issues with the `issuedTo` field

NRPT-39 Fix public redaction unpublished name display and documents showing

---

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.spec.ts
angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts
api/migrations/20210218154834-removeCoorsTickets.js
api/src/importers/coors/tickets-utils.js
api/src/importers/coors/tickets-utils.test.js
api/src/models/master/ticket.js

https://bcmines.atlassian.net/browse/NRPT-664
This PR updates COORS Ticket CSV import to use `CASE_CONTRAVENTION_ID` and `ENFORCEMENT_ACTION_ID` for the source ref ID.
Also removes the old Ticket records that just used `CONTRAVENTION_ENFORCEMENT_ID` for ID.
Test CSV file at https://chat.developer.gov.bc.ca/group/7yTf7q3mWbKBAn2qa?msg=we3GCRdezyc8NXHwd

NRPT-664 Use CASE_CONTRAVENTION_ID and ENFORCEMENT_ACTION_ID for COORS Ticket

---

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts
angular/projects/admin-nrpti/src/app/utils/constants/alc-csv-constants.ts
angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts
api/src/controllers/post/inspection.js
api/src/importers/alc/base-record-utils.js
api/src/importers/alc/base-record-utils.test.js
api/src/importers/alc/datasource.js
api/src/importers/alc/datasource.test.js
api/src/importers/alc/inspections-utils.js
api/src/importers/alc/inspections-utils.test.js
api/src/importers/alc/utils/csv-utils.js
api/src/importers/alc/utils/csv-utils.test.js
api/src/models/lng/inspection-lng.js
api/src/models/master/inspection.js
api/src/models/nrced/inspection-nrced.js
api/src/tasks/import-task.js

https://bcmines.atlassian.net/browse/NRPT-11
This PR adds the ALC Inspection CSV import.  Test file is in Jira ticket
Note:  I decided to use a field called `_sourceRefStringId` instead of something like `_sourceRefAlcInspectionId` for tracking source system IDs.  This is because as we add more import sources, the number of these unique `_sourceRef<system>Id` is starting to get out of hand.  The purpose of `_sourceRefStringId` field is have it be used across all importers instead of creating an unique field for each importer.
The reason `_sourceRefId` isn't used for this is because it is of type `ObjectId` in the models and won't store other types

NRPT-11 ALC Inspections CSV import

---

angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.spec.ts
angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts
angular/projects/admin-nrpti/src/app/services/keycloak.service.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
api/src/controllers/document-controller.js
api/src/controllers/post/administrative-penalty.js
api/src/controllers/post/administrative-sanction.js
api/src/controllers/post/court-conviction.js
api/src/controllers/post/inspection.js
api/src/controllers/post/order.js
api/src/controllers/post/permit.js
api/src/controllers/post/restorative-justice.js
api/src/controllers/post/ticket.js
api/src/controllers/post/warning.js
api/src/swagger/swagger.yaml
api/src/utils/constants/misc.js
api/src/utils/post-utils.test.js

Role controls for ENV-EPD role, includes necessary api and front-end updates.
- API: [NRPT-654](https://bcmines.atlassian.net/browse/NRPT-654)
- UI: [NRPT-353](https://bcmines.atlassian.net/browse/NRPT-353)
Assign yourself only the `admin:env-epd` role
POST to `/api/record` to test api record creation:
`{
"orders": [
{
"recordName": "ENV EPD Role Test",
"recordSubtype": "None",
"issuingAgency": "Environmental Protection Division",
"author": "BC Government",
"issuedTo": {
"type": "Individual",
"companyName": null,
"firstName": "Test",
"middleName": "Middle",
"lastName": "Name",
"fullName": null,
"dateOfBirth": null
},
"OrderNRCED": {
"summary": "NRCED Summary",
"addRole": "public"
},
"OrderLNG": {
"description": "LNG Summary",
"addRole": "public"
}
}
]
}`
Verify success and record …

NRPT-654: implement ENV-EPD role controls in api and nrpti frontend

---

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts
angular/projects/admin-nrpti/src/app/import/import.component.html
angular/projects/admin-nrpti/src/app/import/import.component.ts
angular/projects/admin-nrpti/src/app/services/keycloak.service.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
api/src/controllers/post/administrative-penalty.js
api/src/controllers/post/administrative-sanction.js
api/src/controllers/post/court-conviction.js
api/src/controllers/post/inspection.js
api/src/controllers/post/order.js
api/src/controllers/post/restorative-justice.js
api/src/controllers/post/ticket.js
api/src/controllers/post/warning.js
api/src/swagger/swagger.yaml
api/src/utils/constants/misc.js

Create admin:alc record:
```
POST http://localhost:3000/api/record
{
"orders": [
{
"recordName": "ALC Role Test",
"recordSubtype": "None",
"issuingAgency": "Ministry of Agriculture",
"author": "BC Government",
"issuedTo": {
"type": "Individual",
"companyName": null,
"firstName": "Test",
"middleName": "Middle",
"lastName": "Name",
"fullName": null,
"dateOfBirth": null
},
"OrderNRCED": {
"summary": "NRCED Summary",
"addRole": "public"
},
"OrderLNG": {
"description": "LNG Summary",
"addRole": "public"
}
}
]
}
```
Verify success and record read/write issuedTo read/write have admin:alc role
Create a document in the record:
```POST http://localhost:3000/api/record/{record_id}/document
form-data
fileName: test-file-name.pdf
upfile: browse to your file
```
Verify success document record has …

 NRPT-658 / NRPT-605: Create Role: ALC - API and Front-end

---

angular/projects/admin-nrpti/src/app/import/import-csv/import-csv.component.ts
angular/projects/admin-nrpti/src/app/import/import.component.ts
angular/projects/admin-nrpti/src/app/services/keycloak.service.ts
angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
angular/projects/common/src/app/utils/record-constants.ts
api/migrations/20210302190808-fixCsvImportRecordRoles.js
api/src/controllers/post/administrative-penalty.js
api/src/controllers/post/administrative-sanction.js
api/src/controllers/post/court-conviction.js
api/src/controllers/post/inspection.js
api/src/controllers/post/order.js
api/src/controllers/post/restorative-justice.js
api/src/controllers/post/ticket.js
api/src/controllers/post/warning.js
api/src/controllers/search.js
api/src/importers/cmdb/base-record-utils.js
api/src/importers/cmdb/base-record-utils.test.js
api/src/importers/cmdb/inspection-utils.test.js
api/src/importers/flnr/base-record-utils.js
api/src/importers/flnr/base-record-utils.test.js
api/src/importers/flnr/inspections-utils.test.js
api/src/importers/mis/base-record-utils.js
api/src/importers/mis/base-record-utils.test.js
api/src/importers/mis/inspection-utils.test.js
api/src/swagger/swagger.yaml
api/src/tasks/import-task.js
api/src/utils/constants/misc.js
api/src/utils/post-utils.js

https://bcmines.atlassian.net/browse/NRPT-659
This PR also renamed some of the CSV `sourceSystemRef` values in order to standardize them between the frontend and backend.  A migration has been included to update existing data.
Create `admin:flnr-nro` record:
```
POST http://localhost:3000/api/record
{
"orders": [
{
"recordName": "FLNR-NRO Role Test",
"recordSubtype": "None",
"issuingAgency": "Natural Resource Officers",
"author": "BC Government",
"issuedTo": {
"type": "Individual",
"companyName": null,
"firstName": "Test",
"middleName": "Middle",
"lastName": "Name",
"fullName": null,
"dateOfBirth": null
},
"OrderNRCED": {
"summary": "NRCED Summary",
"addRole": "public"
},
"OrderLNG": {
"description": "LNG Summary",
"addRole": "public"
}
}
]
}
```
Verify success and record read/write …

NRPT-659 Add FLNR-NRO role and other role fixes

---

angular/projects/admin-nrpti/src/app/utils/constants/csv-constants.ts

https://bcmines.atlassian.net/browse/NRPT-694
After a lot of investigation and confusion as to the source of this issue,  I realized that there are different time offsets for daylight savings, so the -7 offset is correct for dates between ~ March and ~ November. To be specific the offset during daylight savings will be -7 and the rest of the time it will be -8, so the moment library is setting the offset correctly for CSV imports as far as I can tell. Because the CSV imports do  not run nightly like the other integrations, we don't have to worry about server side UTC time zone mixups. I did find one bug to fix the time zone on the CMDB CSV import,  and that is the only change in this PR. If I'm missing something drastic here please let me know.

NRPT-694: fixed time zone for CMDB

---

angular/projects/admin-nrpti/src/app/app-routing.module.ts
angular/projects/admin-nrpti/src/app/communications/communications.component.html
angular/projects/admin-nrpti/src/app/communications/communications.component.ts
angular/projects/admin-nrpti/src/app/communications/communications.module.ts
angular/projects/admin-nrpti/src/app/communications/lng-map-info/lng-map-info-resolver.ts
angular/projects/admin-nrpti/src/app/communications/lng-map-info/lng-map-info.component.html
angular/projects/admin-nrpti/src/app/communications/lng-map-info/lng-map-info.component.scss
angular/projects/admin-nrpti/src/app/communications/lng-map-info/lng-map-info.component.spec.ts
angular/projects/admin-nrpti/src/app/communications/lng-map-info/lng-map-info.component.ts
angular/projects/admin-nrpti/src/app/services/factory.service.ts
angular/projects/admin-nrpti/src/app/services/map-layer-info.service.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
angular/projects/common/src/app/models/master/common-models/map-info.ts
api/migrations/20210303191902-addLngMapInfoData.js

- [NRPT-619](https://bcmines.atlassian.net/browse/NRPT-619)

NRPT-619: implement admin component for LNG map updates

---

angular/projects/admin-nrpti/src/app/services/keycloak.service.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
api/src/controllers/post/administrative-penalty.js
api/src/controllers/post/administrative-sanction.js
api/src/controllers/post/court-conviction.js
api/src/controllers/post/inspection.js
api/src/controllers/post/order.js
api/src/controllers/post/restorative-justice.js
api/src/controllers/post/ticket.js
api/src/controllers/post/warning.js
api/src/swagger/swagger.yaml
api/src/utils/constants/misc.js

https://bcmines.atlassian.net/browse/NRPT-610
Create `admin:env-bcparks` record:
```
POST http://localhost:3000/api/record
{
"orders": [
{
"recordName": "ENV-BCPARKS Role Test",
"recordSubtype": "None",
"issuingAgency": "BC Parks",
"author": "BC Government",
"issuedTo": {
"type": "Individual",
"companyName": null,
"firstName": "Test",
"middleName": "Middle",
"lastName": "Name",
"fullName": null,
"dateOfBirth": null
},
"OrderNRCED": {
"summary": "NRCED Summary",
"addRole": "public"
},
"OrderLNG": {
"description": "LNG Summary",
"addRole": "public"
}
}
]
}
```
Verify success and record read/write issuedTo read/write have admin:env-bcparks role
Create a document in the record:
```
POST http://localhost:3000/api/record/{record_id}/document
form-data
fileName: test-file-name.pdf
upfile: browse …
```

NRPT-610 Add ENV BC Parks role

---

api/materialized_views/search/redactedRecordSubset.js

- [NRPT-699](https://bcmines.atlassian.net/browse/NRPT-699)
To test:
Run redacted materialized view: `{"taskType":"updateMaterializedView", "materializedViewSubset":"redactedRecordSubset"}`
Query for Environment Management Act inspections issued to individuals 
`http://localhost:3000/api/public/search?dataset=InspectionNRCED&pageNum=0&pageSize=100&sortBy=-dateIssued&or[issuedTo.type]=Individual&or[issuedTo.type]=IndividualCombined&or[legislation.act]=Environmental%20Management%20Act`
Results should have unredacted issuedTo fields

NRPT-699: publish names if source system is nris-epd

---

angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.ts

https://bcmines.atlassian.net/browse/NRPT-725

NRPT-725 Fix mine record edit

---

api/src/controllers/map-info-controller.js
api/src/swagger/swagger.yaml
api/test/tests/controllers/map-info-controller.test.js

In the `map-info-controller`, `publicGet` and `protectedGet` were hardwired to a `findById` function that, if provided with the `_id`,  of any record, returned that record regardless of user role, record redaction or token authentication. Though it would be difficult for someone to obtain the `_id` of a sensitive record, they would be able to access that record easily if they hit these endpoints. 
`publicGet` and `protectedGet` are yet unused by any services in this project, so this PR removes them from `map-info-controller` and the swagger routes.

NOBUG: removed publicGet and protectedGet from map-info-controller

---

angular/projects/admin-nrpti/src/app/import/import.component.html
angular/projects/admin-nrpti/src/app/import/import.component.ts

Disabled due to no importer code yet.

NRPT-708: Adding button for NRIS-EMLI (disabled for now)

---

angular/projects/admin-nrpti/src/app/import/import.component.html
angular/projects/admin-nrpti/src/app/import/import.component.ts
angular/projects/common/src/app/utils/record-constants.ts
api/README.md
api/openshift/cron.yaml
api/package.json
api/src/integrations/nris-emli/datasource.js
api/src/integrations/nris-emli/datasource.test.js
api/src/swagger/swagger.yaml
api/src/utils/business-logic-manager.js

Needs new ENV var: NRIS_EMLI_API_ENDPOINT to point to emprInspections (defaults to prod api @ https://api.nrs.gov.bc.ca/nrisws-api/v1/emprInspections)

NRPT-707: Adding emli integration.

---

tools/certbot/certbot-bcmi.dc.yaml
tools/certbot/certbot-nrced.dc.yaml

Adding BCMI and NRCED certbot deploy configs for future reference.

NOBUG: Add certbot deploy configs

---

angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-add-edit/mines-administrative-penalty-add-edit.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.html
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.spec.ts
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.html
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.spec.ts
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-resolver.ts
angular/projects/admin-nrpti/src/app/mines/mines-routing.module.ts
angular/projects/admin-nrpti/src/app/mines/mines.module.ts
angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-bcmi-detail/court-conviction-bcmi-detail.component.html
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-bcmi-detail/court-conviction-bcmi-detail.component.scss
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-bcmi-detail/court-conviction-bcmi-detail.component.spec.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-bcmi-detail/court-conviction-bcmi-detail.component.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.ts
angular/projects/admin-nrpti/src/app/records/records.module.ts
angular/projects/admin-nrpti/src/app/records/utils/record-utils.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
angular/projects/common/src/app/models/bcmi/court-conviction-bcmi.ts
angular/projects/common/src/app/models/bcmi/index.ts
api/src/controllers/post/court-conviction.js
api/src/controllers/put/court-conviction.js
api/src/models/bcmi/courtConviction-bcmi.js
api/src/models/bcmi/index.js
api/src/utils/constants/record-type-enum.js

https://bcmines.atlassian.net/browse/NRPT-749
https://bcmines.atlassian.net/browse/NRPT-754
- Court Convictions BCMI add/edit, details
- Other fixes

NRPT-749 NRPT-754 Add Court Convictions BCMI

---

api/migrations/20210708211238-fixAdminPenaltyDisplayName.js
api/src/integrations/bcogc/administrative-penalties-utils.js
api/src/integrations/bcogc/inspections-utils.js
api/src/integrations/bcogc/orders-utils.js
api/src/integrations/bcogc/warnings-utils.js

Issue appears to be limited to files imported from BCOGC. Importer was setting `recordType` equal to `_schemaName`, which has no spaces, so files were showing as having type 'AdministrativePenalty'. Changed `recordType` to equal `displayName` to so type is now 'Administrative Penalty'. Copied this change to other types for consistency, though no other types have spaces. Migration included to fix existing records.

NRPT-560 BCOGC Administrative Penalty display name

---

angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions-resolver.ts
angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions-table/enforcement-actions-table-row/enforcement-actions-table-row.component.html
angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions-table/enforcement-actions-table-row/enforcement-actions-table-row.component.ts
angular/projects/admin-nrpti/src/app/enforcement-actions/enforcement-actions.component.html
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-add-edit/mines-administrative-penalty-add-edit.component.html
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-detail/mines-administrative-penalty-detail.component.html
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.html
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-detail/mines-court-convictions-detail.component.html
angular/projects/admin-nrpti/src/app/sidebar/sidebar.component.html
angular/projects/common/src/app/entity/entity-add-edit/entity-add-edit.component.html
angular/projects/common/src/app/entity/entity-add-edit/entity-add-edit.component.ts
api/src/models/master/administrativePenalty.js
api/src/models/master/courtConviction.js

https://bcmines.atlassian.net/browse/NRPT-749?focusedCommentId=19966

NRPT-749 Fixes to Enforcement Action components

---

api/src/utils/put-utils.js

This PR fixes issue when the update object for PUT contains `_flavourRecords` in both `$set` and `$addToSet`.  `_flavourRecords` is not required in `$set` because newly created flavour IDs are added via `flavourIds` parameter in `editMaster`
https://bcmines.atlassian.net/browse/NRPT-783

NRPT-783 Fix $set and $addToSet conflict on _flavourRecords on PUT

---

angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-administrative-penalty-add-edit/mines-administrative-penalty-add-edit.component.html
angular/projects/admin-nrpti/src/app/mines/mines-enforcement-actions/mines-court-convictions/mines-court-convictions-add-edit/mines-court-convictions-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-add-edit/annual-report-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-add-edit/certificate-amendments-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-add-edit/dam-safety-inspection-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.html
angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.html
angular/projects/common/src/app/legislation/legislation-add-edit/legislation-add-edit.component.ts
angular/projects/common/src/app/legislation/legislation-list-add-edit/legislation-list-add-edit.component.html
angular/projects/common/src/app/legislation/legislation-list-add-edit/legislation-list-add-edit.component.ts
angular/projects/common/src/app/record-association/record-association-edit.component.ts
angular/projects/common/src/app/utils/record-constants.ts

`legislation-list-add-edit` and `legislation-add-edit` components were missing a `recordType` field.

NOBUG fixing legislation autopopulate in record add/edit

---

api/src/importers/coors/datasource.js

https://bcmines.atlassian.net/browse/NRPT-798

NRPT-798 Impoort COORS Ticket as Court Conviction

---

angular/projects/public-nrpti/src/app/records/records-list/search-filters/search-filters.component.html

https://bcmines.atlassian.net/browse/NRPT-796

NRPT-796 update search header text and remove minimize button

---

angular/projects/admin-nrpti/src/app/records/administrative-penalties/administrative-penalty-add-edit/administrative-penalty-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/administrative-sanctions/administrative-sanction-add-edit/administrative-sanction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/annual-reports/annual-report-add-edit/annual-report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/certificate-amendments/certificate-amendments-add-edit/certificate-amendments-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/certificates/certificate-add-edit/certificate-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/construction-plans/construction-plan-add-edit/construction-plan-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/correspondences/correspondence-add-edit/correspondence-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/court-convictions/court-conviction-add-edit/court-conviction-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/dam-safety-inspections/dam-safety-inspection-add-edit/dam-safety-inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/inspections/inspection-add-edit/inspection-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/management-plans/management-plan-add-edit/management-plan-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/orders/order-add-edit/order-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/permits/permit-add-edit/permit-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/reports/report-add-edit/report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/restorative-justices/restorative-justice-add-edit/restorative-justice-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/self-reports/self-report-add-edit/self-report-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/tickets/ticket-add-edit/ticket-add-edit.component.ts
angular/projects/admin-nrpti/src/app/records/warnings/warning-add-edit/warning-add-edit.component.ts

Error when checking value of `centroid[ latitude, longitude ]` fields. Both `latitude` and `longitude` must be valid before creating `centroid[]`, otherwise `centroid = [ undefined, undefined]`

NRPT-813 Fixing error preventing NRPTI record add/edit

---

angular/projects/common/src/app/models/bcmi/certificate-bcmi.ts
angular/projects/common/src/app/models/bcmi/index.ts

This bug was caused by `records-utils` searching for the model `Certificate BCMI` in the common/src/app/models/bcmi directory, but the model did not exist, causing a syntax error. A model for this record type has been created and now the certificate details page will populate.

NRPT-795 certificate details page autopopulate

---

angular/projects/common/src/app/models/nrced/administrative-penalty-nrced.ts
angular/projects/common/src/app/models/nrced/court-conviction-nrced.ts
angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.html
angular/projects/public-nrpti/src/app/records/administrative-penalties/administrative-penalty-detail/administrative-penalty-detail.component.ts
angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.html
angular/projects/public-nrpti/src/app/records/court-convictions/court-conviction-detail/court-conviction-detail.component.ts
api/migrations/20210825181937-unlistedMinesInNRCED.js
api/src/controllers/post/administrative-penalty.js
api/src/controllers/post/court-conviction.js
api/src/models/nrced/administrativePenalty-nrced.js
api/src/models/nrced/courtConviction-nrced.js

https://bcmines.atlassian.net/browse/NRPT-800
For AdministrativePenalty and CourtConviction NRCED flavours. Currently there are no records with `unlistedMine` or `unlistedMineType` records that are published to NRCED, so a migration was done only to ensure `AdministrativePenaltyNRCED` and `CourtConvictionNRCED` have blank `unlistedMine` and `unlistedMineType` fields. Publishing records to NRCED after this PR is merged will update the fields accordingly.

NRPT-800: Adding unlistedMine to NRCED records

---

tools/api/api.dc.yaml

As mentioned previously, the NRIS-EMLI importer is ready but was left inactive, as NRIS-EMLI and BCMI are not yet ready.
The EMLI importer is affected by the following environment variables:
* [`angular/projects/admin-nrpti/src/env.js`](https://github.com/bcgov/NRPTI/blob/task/research-enabling-emli-importer/981/angular/projects/admin-nrpti/src/env.js):
```js
window.__env.FEATURE_FLAG = {
"nris-emli-importer": false
};
```
* No changes were made here.
* [`tools/api/api.dc.yaml`](https://github.com/bcgov/NRPTI/blob/task/research-enabling-emli-importer/981/tools/api/api.dc.yaml), for the `nrpti-api` container:
```yaml
- name: NRIS_EMLI_DOCUMENT_BINARIES_ENABLED
value: 'false'
- name: NRIS_EMLI_API_ENDPOINT
value: 'https://api.nrs.gov.bc.ca/nrisws-api/v1/emprInspections'
```
* [The existing …

Add environment variables for NRIS-EMLI importer

---

api/src/controllers/document-controller.js

Drive-by code review.  The comment says the expiry is for 5 minutes, but the call to `getSignedURL` takes `seconds` as a parameter.

NOBUG: Fixing 3.47 days expiry => 5 minutes, as the comment suggests.

---

api/src/integrations/nris-epd/datasource.js

NRIS importer extracts data in one-month chunks. If it fails to get data for a certain month it sets a final status as Failure. However, it still continues getting data for the subsequent months. 
The log analysis showed that failures occur at the first few date intervals.  Because of that the order for extraction does not matter. 
The proposed change may help to fix the issue because there are higher chances that the import will succeed if attempted multiple times.

995 nrpti change chronological order of records being uploaded from nris epd

---

.github/workflows/FrontEnd-Lint-Test.yml
angular/projects/public-lng/src/app/home/home.component.html

Updated information on LNG homepage to direct users to new resources of information. 
Downgraded ubuntu to run GitHub actions tests.

Redirect LNG users to new resources

---

angular/projects/admin-nrpti/src/app/services/keycloak.service.ts
angular/projects/admin-nrpti/src/app/utils/constants/misc.ts
angular/projects/common/src/app/utils/record-constants.ts
angular/projects/global/src/lib/utils/utils.ts
api/migrations/20230713184323-addWLRSRole.js
api/src/controllers/post/administrative-penalty.js
api/src/controllers/post/administrative-sanction.js
api/src/controllers/post/court-conviction.js
api/src/controllers/post/inspection.js
api/src/controllers/post/order.js
api/src/controllers/post/permit.js
api/src/controllers/post/restorative-justice.js
api/src/controllers/post/ticket.js
api/src/controllers/post/warning.js
api/src/swagger/swagger.yaml
api/src/utils/constants/misc.js

- Add a new admin:wlrs role to NRPTI for the Ministry of Water, Land and Resource Stewardship (WLRS) users.
- This allows users with the admin:wlrs role to create and view records records; records created with this role are only able to assign WLRS as the Issuing Agency.
- By default, admin:wlrs roles can't see Entity information (personal information) unless they created the record.
- Add a migration to update the roles in the db so admin:wlrs can read existing records.

1060 new issuing agency

---

api/materialized_views/search/redactedRecordSubset.js
api/migrations/20230727000836-unredactMinistryOfForests.js
api/migrations/README.md
api/src/utils/constants/misc.js

Changelog:
* Update how redacted records are updated. Issue with updating redacted records from NRPTI admin is resolved.
* Ministry of Forests is added as an AUTHORIZED_PUBLISH_AGENCIES, so future Administrative Sanctions records are automatically published to NRCED
* Migration to re-add "issuedTo" objects from the master record to AdministrationSanctionNRCED records in the redacted_record_subset collection. These were initially removed to unpublish names from appearing in Administrative Sanction records.
* Added a migration README to the repo

1067 unredact admin sanctions

---

angular/projects/public-nrpti/src/app/records/records-row/records-table-row.component.ts
api/package-lock.json
api/package.json

Removed special handling for Administrative Sanctions: 
Regarding descriptions, these records are now treated like regular records and will show the missing information.
Fix several outdated dependencies using `npm audit fix`

Removed special handling for Administrative Sanctions. 

---

api/src/importers/coors/utils/csv-utils.js
api/src/utils/constants/misc.js

Changelog:
* Revert update to issuingAgency for Conservation Officer Service (no longer shows BC Energy Regulator)
* Check COORS import (Court Convictions and Tickets only) for "Water Sustainability Act" to apply the proper issuing Agency (BC Energy Regulator)

fix issuing agency, add check for water sus act

---

api/Dockerfile
docker-compose.yaml
mongoSeed/init/create-db.js

- Creation of a `Dockerfile`, `docker-compose.yaml`, and `create-db.js` seed file.
- The Dockerization will allow creation of a Mongodb database and its respective collections set by default, reducing the onboarding time of a developer in manually getting the docker image, and setting up their database for development.
1. The Database can be readily setup much faster than the current manual process
* *The developer still needs to seed their own data*
2. No need to worry about correctly installing dependencies in the API when doing development work in the front end.
3. Docker images are grouped together appropriately
- The commented out section in the docker-compose is in hopes of the API later getting a health endpoint (to maintain …

[NRPTI-1115] DEV FEATURE** Create Dockerfiles and docker-compose

---

angular/projects/public-nrpti/src/app/records/utils/record-utils.spec.ts
angular/projects/public-nrpti/src/app/records/utils/record-utils.ts

- Adds outcomeDescription field to ALL CSV files
- Includes testing

[NRPTI-1112] Add outcome description values to CSV outputs in NRCED

---

api/src/importers/coors/court-conviction-utils.js
api/src/importers/coors/court-conviction-utils.test.js

- Used the correct location field in non GTYJ enforcement outcome logic
- Changed tests affecting this piece of functionality

[NRPTI-1097] BUG: Fix location field in COORS court conviction importer

---

api/src/integrations/core/datasource.js

- Hotfix to the CORE importer to import all mines regardless of permits
- This will import permits even if they're exploratory permits

 [HOTFIX][NRPTI-1161]** Hotfix to import all mines from core

---

api/src/integrations/bcogc/administrative-penalties-utils.test.js
api/src/integrations/bcogc/orders-utils.test.js
api/src/integrations/bcogc/warnings-utils.test.js
api/src/integrations/epic/base-record-utils.test.js
api/src/integrations/epic/certificates-amendment-utils.test.js
api/src/integrations/epic/certificates-utils.test.js
api/src/integrations/epic/epic-record-type-enum.js
api/src/integrations/epic/epic-record-type-enum.test.js
api/src/integrations/epic/epic-utils.test.js
api/src/integrations/epic/inspections-utils.test.js
api/src/integrations/epic/orders-other-utils.test.js
api/src/integrations/epic/orders-utils.test.js

- Add additional testing for the EPIC integration
- Fix cleanup in BCOGC test with mongoose mocks
- Fix bug in `epic-record-type-enum.js` where no record types were returnable by `getSome` method
| File                         | Old Coverage | New Coverage | Improvement |
|------------------------------|--------------|--------------|-------------|
| *integrations/epic*                           | 45.54%        | **85.81%**        | +40.27%      |
| --base-record-utils.js                      | 38.96%        | **80.52%**        | +41.56%       |
| --certificates-amendment-utils.js   | 0%        | **83.33%**        | +83.33%      |
| --certificates-utils.js                         | 0%        | **83.33%**        | +83.33%      |
| …

[TECH-DEBT][NRPTI-1167]** add additional testing for EPIC integration

---

api/migrations/20240216204922-adminEnvEpdToNrisEpdRecords.js
api/src/controllers/post/inspection.js
api/src/controllers/post/inspection.spec.js

- Add migration to update existing `{"sourceSystemRef":"nris-epd"}` records (master and NRCED flavour) to have the `read` and `write` role of `admin:env-epd`
- Update the `inspection.js` file to add `admin:env-epd` to master and NRCED flavour NRIS-EPD items imported into NRPTI if the `sourceSystemRef` is `nris-epd`
- Add testing

[FIX][NRPTI-#1146] - Update NRIS-EPD integration to give admin:env-epd role, add migration to update existing NRIS-EPD records

---

api/migrations/20240226205826-removeErroneousFishAndSeafoodActRecords.js

- Add migration to delete all Inspections with the legislative act "Fish and Seafood Act" on `nrpti` and `redacted_record_subset` collection.
- This will keep all non-Inspection records (Tickets, Administrative Penalties, etc.)

[FIX][NRPTI-#1103] - Remove all "Fish and Seafood Act" Inspections from Collection

---

angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
angular/projects/public-nrpti/src/app/records/records-list/records-list.component.html
angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts
angular/projects/public-nrpti/src/app/services/factory.service.ts

- Overwrote the default functionality of **autofocus** query param on records to search for single record instead of just expanding the record (Records were being buried multiple pages back depending on the filter values in the url)
- Corrected whitespace issue in `html` file
- Changed truthy value in `records-list.component` to boolean to allow for empty strings

DRAFT [NRPTI-1191] FEATURE** autofocus param searches for specific record

---

angular/projects/admin-nrpti/src/app/records/records-rows/records-table-row.component.ts
angular/projects/admin-nrpti/src/app/services/factory.service.ts
angular/projects/common/src/app/legislation/legislation-add-edit/legislation-add-edit.component.spec.ts
angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts

- Disable edit button only if the user is not in any of admin:bcmi/lng/nrced roles

[BUG-FIX][NRPTI-1219] - Permissions not working as expected

---

api/src/integrations/bcogc/administrative-penalties-utils.test.js
api/src/integrations/bcogc/datasource.js
api/src/integrations/bcogc/datasource.test.js
api/src/integrations/bcogc/inspections-utils.test.js
api/src/integrations/bcogc/orders-utils.test.js

- Added a missing parameter to transformRecord() calls in BCOGC integration utility tests
- tests now pass
- Also improved handling in BCOGC  datasource.js. If a call to get the actName fails, the actCode will now be passed in. This is perfectly acceptable behaviour as many records are already being created with just the actCode instead of the associated actName.

[FIX][NRPTI-1226] added missing parameter to transformRecord calls in BCOGC integration utils tests

---

api/package-lock.json
api/package.json

There were 17 critical vulnerabilities identified by ```npm audit```. 14 of those have been addressed by the changes listed below. 
- Updated babel translator packages (dependency of jest)
- Updated express version
- Running ```npm audit fix``` applied non-breaking updates to several other packages
Update mongoose to >=5.13.20
- Despite showing no breaking changes, updating to >=5.13.4 causes 2 test suites (nris datasource tests) to not run. They fail with the error ```require-at: not a directory: <my-project-dir>/api```. The actual functionality that these tests describe appear to all work as intended on this version, but I was unable to diagnose what was causing the tests to fail.
- This …

[UPDATE][NRPTI-1149] Update dependencies to address critical vulnerabilities

---

angular/projects/common/src/app/legislation/legislation-list-detail-public/legislation-list-detail.component.spec.ts
angular/projects/public-nrpti/src/app/services/acts.service.spec.ts
angular/projects/public-nrpti/src/app/services/acts.service.ts
api/src/controllers/acts-regulations-controller.js
api/src/tests/controllers/acts-regulations-controller.test.js

This ticket was created as a learning opportunity around testing in NRPTI. A test case has been created in both the frontend and backend. As well, one of the tests brought to light an uncaught bug in the error handling for a method (parseTitleFromXML). that bug has been corrected as part of this work.
- legislation-list-detail component: added test that, if backend API is unavailable, instead of translating an actCode, it returns the same actCode
- acts.service: added boilerplate test that checks for creation
- also fixed some copy-paste errors in the comments for this service
- acts-regulations-controller: made parseTitleFromXML function exported for testing. Added test for positive and negative cases for title being present. Updated …

[TASK][NRPTI-1223] add two tests for work around act name changes

---

angular/projects/admin-nrpti/src/app/records/records-resolver.spec.ts
angular/projects/admin-nrpti/src/app/records/records-resolver.ts
angular/projects/admin-nrpti/src/app/records/utils/record-utils.ts
angular/projects/public-nrpti/src/app/records/records-list/records-list-resolver.ts
angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
api/src/controllers/acts-regulations-controller.js
api/src/controllers/search.js

* Added function in backend to get act code from act title using mapping table 'acts_regulations_mapping'
* Added logic in backend to check legislation acts when searching
* Removed function from frontend as not to cause duplication and references in tests

[BUG][NRPTI-1231] Fix bug where manually added records are not appearing in the nrced csv export

---

angular/projects/admin-nrpti/src/app/records/records-resolver.ts
angular/projects/public-nrpti/src/app/records/utils/record-utils.ts

* Add logic to lookup legislation act codes during CSV export, fixing a bug where the end user would be shown the act code instead of the friendly title.

[BUG][NRPTI-1235] Check legislation act codes during CSV export

---

api/src/integrations/integration-utils.js
api/src/integrations/nris-emli/datasource.js
api/src/integrations/nris-emli/datasource.test.js
api/test/setEnvVars.js

Add support for redacted inspection reports to automatically be published in the EMLI integration. Previously only Final reports were published but we can now automatically publish reports created after June 1st as they have been redacted and not contain any personal information.
* Added logic to publish attachments with a fileType of 'Report', attachment comment of 'Inspection Report' and a date after the environment variable NRIS_ATTACHMENT_DATE which defaults to June 1st.
* Expanded test case to cover new attachment logic

[FEATURE][NRPTI-1125] Automated publishing of redacted mines act inspection reports

---

.github/ISSUE_TEMPLATE/bug.md
angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.html
angular/projects/admin-nrpti/src/app/mines/mines-record-add/mines-record-add.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.html
angular/projects/admin-nrpti/src/app/mines/mines-records-detail/mines-records-detail.component.ts
angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.html
angular/projects/admin-nrpti/src/app/mines/mines-records-edit/mines-records-edit.component.ts
angular/projects/admin-nrpti/src/app/records/utils/record-utils.ts
angular/projects/common/src/app/utils/record-constants.ts
api/migrations/20240619192233-updateBCMICollectionTypeField.js
api/src/controllers/mine-controller.js
api/src/integrations/core/datasource.js
api/src/integrations/core/permit-utils.js
api/src/models/bcmi/permit-bcmi.js
api/src/models/master/permit.js

* Support for new permit code 'ALG' in both CORE cron job and front end
* Migration to update existing BCMI collections with type of 'ALG'
* Additional minor unrelated spelling and linting fixes

[BUG][NRPTI-1233] Amalgamated permits not showing in BCMI

---

api/migrations/20240619192233-updateBCMICollectionTypeField.js

The original migration was only looking for permits with _schemaName == PermitBCMI. It turns out that many of the mine permits actually have _schemaName == Permit. The migration has been updated to capture both these sets of permits when updating the document collection.
- Fixed BCMICollection update migration by including missing permits from the available records to check.

[FIX][NRPTI-1233] updated bcmi collection migration to properly find all relevant permits

---

api/src/integrations/core/datasource.js
api/src/integrations/core/datasource.test.js
api/src/integrations/core/permit-utils.js
api/src/integrations/core/permit-utils.test.js

Previously only the most recent valid permit was selected for a mine and records processed for the permit. However requirements changed and now both M and MX records need to be publicly available. A hotfix [hotfix](https://github.com/bcgov/NRPTI/pull/1162) was deployed but did not address the underlying problem leading to syncing issues. This PR attempts to properly implement a solution.
Replaces getMinePermit() with getMinePermits() and separates the logic out into multiple methods so that createMinePermit() and updateMinePermit() can process multiple mine permits instead of only the currently selected valid Mine Permit. This allows both MX and M permits and collections for a single mine to be processed during the cron run.

[BUG][NRPTI-1242] Add support for creating & updating permits from multiple permit codes

---

api/src/controllers/acts-regulations-controller.js

- Replaces call to this.parseTitleFromXML with exports.parseTitleFromXML as using 'this' is not valid outside of a class.
- This bug was preventing the cronjobs in the test environment from completing successfully

[BUG][NRPTI-1250] Fix acts update function call

---

api/src/controllers/collection-controller.js
api/src/controllers/search.js
api/src/integrations/core-documents/datasource.js
api/src/integrations/core-util.js
api/src/integrations/core/datasource.js
api/src/models/bcmi/collection-bcmi.js

- Move all core token refresh logic to a seperate Core Utils class used by both the core-documents integration and core integration.
- Cleanup search logging by changing logs to 'debug' level and setting the console output level to 'info'
- Add permitNumber to BCMICollections to store the correct permit number to be used later for displaying in BCMI.
- Fix bug where admin users couldn't see public records due to missing the 'public' role.

[FEATURE][NRPTI] Move token refresh logic to core-utils, cleanup search logging

---

api/src/controllers/agencies.js
api/src/utils/business-logic-manager.js

When deciding if a record needs redaction, one of the checks is of the issuing agency and making sure that it has authority to publish records. BUT due to the change to using an intermediate code for representing agencies, this check was often comparing the actual agency name to the agency code and authorized agencies were not getting through. The first version of the fix included an async function that required many other upstream functions to be converted to async. Ultimately, this task was not able to be successfully completed in a timely manner. A bandaid function was created using hardcoded values. These will eventually be out of date and the bug behaviour will start appearing again. #1258 was created to address this tech debt.
- …

[FIX][NRPTI-1239] Amp record redaction fix (temporary workaround)

---

api/migrations/20240722204849-fix-improperly-redacted-records.js

This migration fixes improperly redacted administrative records. 
When a record is added to NRPTI, another matching record is also created in the redacted_record_subset collection. This record has all necessary redactions applied to it and is where NRCED gets its data from. Due to a bug, some records were improperly redacted. This migration finds all records that meet the standard for NOT being redacted, and then updates the associated records in both collections to have all the data that shouldn't have been redacted.

[MIGRATION][NRPTI-1239] migration to fix improperly redacted AMPs

---

angular/projects/public-nrpti/src/app/records/records-list/records-list.component.ts
angular/projects/public-nrpti/src/app/records/utils/record-utils.ts
api/src/integrations/core-documents/datasource.js
api/src/integrations/core-documents/datasource.test.js
api/src/integrations/core-util.js
api/src/integrations/core/datasource.test.js
api/src/integrations/core/mine-utils.js
api/src/integrations/integration-utils.test.js
api/src/integrations/nris-emli/datasource.js
api/src/integrations/nris-emli/datasource.test.js
api/src/integrations/nris-epd/datasource.js
api/src/models/bcmi/mine-bcmi.js

- Add mineNo to core mine records
- Update NRIS-EPD & NRIS-EMLI importers to link better to core mines using the projectName field
- Add support for searching in NCRED via project/projectName
- Fixing of automated tests

[FEATURE][NRPTI-1262] redirect link on bcmi that directs to the corresponding search on nrced
